### ISSUE TITLE
Fill or create commands give blank prompt, no buttons, no results. (bug)

### ISSUE THREAD

**Issue by Pachtjuilaard** [carlonicora/obsidian-rpg-manager#11]
All commands are working as intended on a clean vault, but in my working D&D vault, I can't use any of the commands to create or fill notes with templates. They result in a blank pop up with no buttons (except the x button in top right), and there's no output.

Console: 
Uncaught (in promise) TypeError: (metadata.frontmatter.tags || []).forEach is not a function
    at eval (plugin:obsidian-rpg-manager:912:43)
    at Array.forEach (<anonymous>)
    at ClueModal.initialiseCampaigns (plugin:obsidian-rpg-manager:909:35)
    at ClueModal.onOpen (plugin:obsidian-rpg-manager:840:10)
    at ClueModal.e.open (app.js:1:1128457)
    at FileFactory.eval (plugin:obsidian-rpg-manager:1362:85)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-rpg-manager:43:61)
    at new Promise (<anonymous>)
    at __async (plugin:obsidian-rpg-manager:27:10)
eval	@	plugin:obsidian-rpg-manager:912
initialiseCampaigns	@	plugin:obsidian-rpg-manager:909
onOpen	@	plugin:obsidian-rpg-manager:840
e.open	@	app.js:1
eval	@	plugin:obsidian-rpg-manager:1362
eval	@	plugin:obsidian-rpg-manager:43
__async	@	plugin:obsidian-rpg-manager:27
initialise	@	plugin:obsidian-rpg-manager:1356
callback	@	plugin:obsidian-rpg-manager:2642
yH	@	app.js:1
t.onChooseItem	@	app.js:1
t.onChooseSuggestion	@	app.js:1
t.selectSuggestion	@	app.js:1
e.useSelectedItem	@	app.js:1
(anonymous)	@	app.js:1
e.handleKey	@	app.js:1
e.onKeyEvent	@	app.js:1

**Comment by carlonicora** [comment]
@Pachtjuilaard thanks for the bug report.
I tried to reproduce locally, but without success. It's like there is an error in the tags in one of your files.

I have patched a new version in the [dev branch](https://github.com/carlonicora/obsidian-rpg-manager/tree/dev): can you pull it and copy main.js, manifest.json and styles.css and give it a go?

If that works I will release a patch with version 0.3.8 today

**Comment by carlonicora** [comment]
PS: I managed to reproduce the bug. By setting the frontmatter as 
```
---
tags: [[somethinglikethis]]
---
```

The error is triggered. Working on it now.

**Comment by Pachtjuilaard** [comment]
It's still the same for me, it works in a completely clean vault until I import my D&D notes in there. I'm already using tags like #location, #character and #session, and if I remove all tags, the plugin works again. I'll try and reformat the tags that I have to make it work with your plugin.
Would it be possible to write an error message, showing which tags are incorrectly formatted?

**Comment by Pachtjuilaard** [comment]
The plugin immediately stops working when I don't enclose tags in single brackets. 
"tags: [session-logs]" works, but "tags: session-logs" makes the plugin stop working.

**Comment by carlonicora** [comment]
Fixed in [v0.3.8](https://github.com/carlonicora/obsidian-rpg-manager/releases/tag/0.3.8)

**Comment by carlonicora** [comment]
NOT FIXED

@Pachtjuilaard thanks for the info. Working on those right now

**Comment by carlonicora** [comment]
Fixed in [v0.3.9](https://github.com/carlonicora/obsidian-rpg-manager/releases/tag/0.3.9)
