### ISSUE TITLE
PCs and NPCs pronouns

### ISSUE THREAD

**Issue by thegiftofgabes** [carlonicora/obsidian-rpg-manager#12]
Character elements need to have a line for pronouns in the frontmatter so that they appear in the summary block together with their portrait, goals, etc,

**Comment by carlonicora** [comment]
Pronoun added to NPC info table and Synopsis (both PC and NPC).
Required the frontmatter `pronoun:` set to 'T'/'S'/'H' (They/She/He)

Release in [v0.3.12](https://github.com/carlonicora/obsidian-rpg-manager/releases/tag/0.3.12)
