### ISSUE TITLE
I'd like to add made up calendar / Fantasy Calendar Integration

### ISSUE THREAD

**Issue by Sweet0-0** [carlonicora/obsidian-rpg-manager#125]
Hay! As the title says I have my own calendars to work with in my world building. Would it be possible for it to support plugging in your own calendars. The age calculating feature is really cool and it'd be cool to

if not would it be possible to simply adjust it's output?

**Comment by carlonicora** [comment]
Hi @Sweet0-0  
Thanks for the request.

Would it be beneficial to you if I were to integrate Fantasy Calendar into RPG Manager?

Would that sort your challenges?

**Comment by tmilktoast** [comment]
> Hi @Sweet0-0 Thanks for the request.
> 
> Would it be beneficial to you if I were to integrate Fantasy Calendar into RPG Manager?
> 
> Would that sort your challenges?

I'm not the original poster, but that sounds like a great idea.

**Comment by Sweet0-0** [comment]
> Hi @Sweet0-0 Thanks for the request.
> 
> Would it be beneficial to you if I were to integrate Fantasy Calendar into RPG Manager?
> 
> Would that sort your challenges?

I'm the original poster, and yes that wold be incredible actually 💜

**Comment by carlonicora** [comment]
Note to self: [Fantasy Calendar API Reference](https://github.com/fantasycalendar/obsidian-fantasy-calendar/blob/master/src/@types/api.d.ts)

**Comment by carlonicora** [comment]
## Implementation notes

### Required Changes

- [ ] Select the type of calendar during campaign creation (_if FC is installed AND if a specific FC Calendar is present, default Gregorian_)
- [ ] Select the type of calendar in the campaign view (_if FC is installed AND if a specific FC Calendar is present, default Gregorian_)
- [ ] Read the FC Date from the frontmatter (_if FC is installed AND if a specific FC Calendar is present, default RPG Manager  date_)
- [ ] Specify the date of an event in a scene (_if FC is installed AND if a specific FC Calendar is present, default Gregorian_)

### Questions

- Can I add an Obsidian note in the FC calendar?
