### ISSUE TITLE
Add relationship links to the bottom of the note to allow Obsidian to use the information for the graph diagram

### ISSUE THREAD

**Issue by carlonicora** [carlonicora/obsidian-rpg-manager#131]

**Comment by StarSword-C** [comment]
Yes, please!

**Comment by cjolson** [comment]
If you add links as `[[Link Name|]]`, they can be "invisible". Not sure which is "best", but if the intent is only to add the link in the graph view and you want to avoid clutter that would accomplish that.

**Comment by carlonicora** [comment]
@cjolson the problem is not as easy to solve as it seems. The links are dynamically generated and can be reversed. A dynamically generated link means that it is created at runtime, hence I would have to edit the file every time a new relationship is added or removed. This creates a massive overhead of read/write.
Also, another consideration is how to manage the relationship between plot elements... something the crew carefully before starting to write code and slow down the entire plugin

**Comment by sigrunixia** [comment]
Confirmed It is Working in 3.4.05
