### ISSUE TITLE
Flickering screen and jumping cursor while adding text to Acts and Scenes

### ISSUE THREAD

**Issue by matthewbivins** [carlonicora/obsidian-rpg-manager#146]
It doesn't seem to happen in NPC or Character pages…mostly Scenes and Acts that I have noticed this far. I'm uploading an example of the behavior. I'm using some custom CSS, but the Default theme, and I've tried it without the custom CSS too, with the same results. I don't think that I have a plugin that is contributing, but if I turn off Live Preview it doesn't happen. Thank you!

https://user-images.githubusercontent.com/2893243/194734602-d12f6d37-7b81-4d2d-b693-8d3360e2436e.mp4

**Comment by carlonicora** [comment]
Hi @matthewbivins 
This has been solved in the upcoming `v3.0` release, which will be available next week

**Comment by matthewbivins** [comment]
@carlonicora this works beautifully now…and v3 is absolutely fantastic, as well!! you are on fire!!
