### ISSUE TITLE
how to use dates in RPG Manager

### ISSUE THREAD

**Issue by StarSword-C** [carlonicora/obsidian-rpg-manager#147]
More of a question than an issue: I'm trying to use the date and age functions for character pages but I don't know what formatting to use to set them. I have a canon character (from the Golarion/Lost Omens setting for Pathfinder) who was born in 4629 AR and dies of old age at the start of my campaign in 4716 AR, plus whatever dates and ages my PCs use and so on.

**Comment by StarSword-C** [comment]
Right now it's giving ages of 0 regardless of what dates I use.

**Comment by carlonicora** [comment]
Hi @StarSword-C 

Please check the [frontmatter documentation](https://github.com/carlonicora/obsidian-rpg-manager/blob/master/frontmatter.md):
1. RPG Manager currently supports Gregorian Calendar only
2. To generate the age, RPG Manager requires the campaign `currentDate` to be set

**Comment by StarSword-C** [comment]
> Hi @StarSword-C
> 
> Please check the [frontmatter documentation](https://github.com/carlonicora/obsidian-rpg-manager/blob/master/frontmatter.md):
> 
>     1. RPG Manager currently supports Gregorian Calendar only
> 
>     2. To generate the age, RPG Manager requires the campaign `currentDate` to be set

Ok, cool. I was hoping I could just use a year but I guess I have to make up months and days. Thanks for answering.
