### ISSUE TITLE
Date agnostic or optional age

### ISSUE THREAD

**Issue by thegiftofgabes** [carlonicora/obsidian-rpg-manager#15]
Sometimes the age of a character is not relevant, uncertain, or outright unknowable. Also, there are many reasons why an in-campaign calendar may be unnecessary, unreliable, or shifting.

In any case, I suppose that birth/death dates could be optional. Additionally, we could be able to simply add an age number or descriptor (17, 357, unknown, unknowable, etc).

**Comment by carlonicora** [comment]
@thegiftofgabes wouldn't the same apply to the pronoun? No pronoun means no line in the table?

**Comment by thegiftofgabes** [comment]
It always appears as "Dob or campaign date missing" to me.

**Comment by carlonicora** [comment]
Date is now shown in character info table only if valid.

https://github.com/carlonicora/obsidian-rpg-manager/releases/tag/0.3.14
