### ISSUE TITLE
Minor Graphical Interaction: Headers and New Codeblock

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#152]
In the case where a note has H1, H2, H3, and so on up top on a note near the bottom of YAML, that contains a RPGM code block, the Header and new Component Die can now overlap visually if there is not adequate spacing between the first component die code block and a header.

![rpg_codeblock](https://user-images.githubusercontent.com/68425372/194774505-e73228e4-93e2-44ba-99db-6f52d35265f0.png)

I am attaching the screenshots using a custom theme, but I did test this using default theme as well. Default theme makes it hard so see the example as the color of the die and header is the same.

## My Original Code
![rpg_codeblock_headers1](https://user-images.githubusercontent.com/68425372/194774551-37997d16-b606-4075-9238-cf2fd06c1208.png)

## Fixed Code
![rpg_codeblock_headers1_space](https://user-images.githubusercontent.com/68425372/194774564-e010aaf2-bba5-475c-be6c-8a9cba19646c.png)

## Code after H1 was removed, and Obsidian Linter added it back in
![rpg_codeblock_headers_linter](https://user-images.githubusercontent.com/68425372/194774582-a0e7d31f-d9fe-4d4e-bdf4-7fd0d3bc8358.png)

Judging by the actions of Obsidian Linter, I would say this is a first-time install/first time 3.0 upgrade issue only with a specific use case, as it only targets those who use headers near the bottom of the YAML borders. I'm in the process of renaming all these headers to something more useful, so force myself keeping them in some capacity. 

### Proposed Solution From A Novice
1. When injecting RpgManagerData (and probably any code block, to be honest) into a note for the first time or on 3.0 upgrade, include a check for nearby note elements and add 1-2 line break if there is something detected. 
2. Alternatively, Include 1-2 line breaks by default around the blocks by default. 

Edit: Changed title to specify markdown headers as I noticed the topic below also used the header verbiage, but is talking about a separate header.

**Comment by carlonicora** [comment]
@sigrunixia I did move the d20 icon on top of the next element on purpose, as I thought that the RpgManagerData would always have been directly on top of the first RpgManager codeblock.
I see now that the idea was smart in an ideal world, but in the real world causes only troubles! :)

Will change and revert

**Comment by carlonicora** [comment]
Available in `v3.0.0-1`
