### ISSUE TITLE
Report: ABT/Story Circle Disable Then Re-Enable Inconsistencies

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#153]
I may have a _**specific niche case**_ as in one of my "campaigns" I was reconverting story chapters back into a campaign format, and not in order, so some older acts are not fully done and some are.

## Situation
Not all of my acts, scenes, and adventures had fully filled out ABT/Story Circle descriptions, but some did. Upon upgrade, those are now disabled by default, which is okay. When re-enabled, those notes that had the ABT/SC descriptions repopulated just fine. 

Those that did not, required either a combination of refill with act/scene + restart obsidian, or create new act/scene + restart obsidian, in order to get the **RpgManagerData** and **RPGManager Header** code blocks to show up. I have not been able to generate a specific behavior as of yet to report. Sometimes removing the "" besides the YAML keys worked, sometimes it did not. 

I'll update as I gather more.

### Obsidian Errors For This
It seems to not like it when null was chosen as the fill.

> plugin:rpg-manager:9455 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
>     at Scene.get isCurrentlyRunning [as isCurrentlyRunning] (plugin:rpg-manager:9455:92)
>     at SceneHeaderSubModel.eval (plugin:rpg-manager:2809:111)
>     at Generator.next (<anonymous>)
>     at fulfilled (plugin:rpg-manager:44:24)
> plugin:rpg-manager:9455 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
>     at Scene.get isCurrentlyRunning [as isCurrentlyRunning] (plugin:rpg-manager:9455:92)
>     at SceneHeaderSubModel.eval (plugin:rpg-manager:2809:111)
>     at Generator.next (<anonymous>)
>     at fulfilled (plugin:rpg-manager:44:24)
> plugin:rpg-manager:9455 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
>     at Scene.get isCurrentlyRunning [as isCurrentlyRunning] (plugin:rpg-manager:9455:92)
>     at SceneHeaderSubModel.eval (plugin:rpg-manager:2809:111)
>     at Generator.next (<anonymous>)
>     at fulfilled (plugin:rpg-manager:44:24)
> plugin:rpg-manager:9455 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
>     at Scene.get isCurrentlyRunning [as isCurrentlyRunning] (plugin:rpg-manager:9455:92)
>     at SceneHeaderSubModel.eval (plugin:rpg-manager:2809:111)
>     at Generator.next (<anonymous>)
>     at fulfilled (plugin:rpg-manager:44:24)
> plugin:rpg-manager:9455 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
>     at Scene.get isCurrentlyRunning [as isCurrentlyRunning] (plugin:rpg-manager:9455:92)
>     at SceneHeaderSubModel.eval (plugin:rpg-manager:2809:111)
>     at Generator.next (<anonymous>)
>     at fulfilled (plugin:rpg-manager:44:24)
> plugin:rpg-manager:9455 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
>     at Scene.get isCurrentlyRunning [as isCurrentlyRunning] (plugin:rpg-manager:9455:92)
>     at SceneHeaderSubModel.eval (plugin:rpg-manager:2809:111)
>     at Generator.next (<anonymous>)
>     at fulfilled (plugin:rpg-manager:44:24)

**Comment by carlonicora** [comment]
Hi @sigrunixia 

I think I understand the problem, and it lies on the fact that some hierarchical elements don't find their parents. I think I can put some better error management there.

Thanks for the report

**Comment by carlonicora** [comment]
Available in `v3.0.0-1`
