### ISSUE TITLE
Language Suggestion: The "Vocals"

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#155]
## Scope
This is a basic suggestion that will not change the functionality of the application. Only the language used in two relationships for clarity.

## Summary
Admittedly, when I first saw "biunivocal" and "univocal" I had to pull out my dictionary. I roughly knew what they meant by context, but it is not common by any means. Even reading the documentation on it I got what it was trying to convey, but it was technical jargonist for sure. When I have a fresh set of eyes, I'll take a look at the doc and suggest some changes to that as well.  

## Suggested Changes for the Components
1. Biunivocal could be changed to **Bidirectional**. 
2. Univocal could be changed to **Unidirectional**. 

Both of these are more common adjectives and have use in other industries. They will be immediately recognizable.

**Comment by carlonicora** [comment]
@sigrunixia Thanks for the suggestion! I admit I had some issues coming up with good wording for those two names...

What about `one way` and `two ways`? Would you consider them understandable? I feel they are simpler, but failing that your suggestion makes more sense than univocal and biunivocal

**Comment by carlonicora** [comment]
available in `v3.0.0-2`

**Comment by sigrunixia** [comment]
This issue is confirmed adjusted in v3.0.0-2 testing build.

A two-way relationship is now referred to as bidirectional.
A one-way relationship is now referred to as unidirectional. 

The "parent" or "origin" of the directionality (who initiated, who owns) is something I plan to further clarify in documentation, and visually will suggest be further addressed in design updates down the road.
