### ISSUE TITLE
Feature Request: Limit Scene Selector on Sessions

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#156]
**Scope**: Similar to Issue #154, this is a later stage problem that arises as the amount of scenes grows.

## Summary
Scene Selector currently pulls from the total amount of scenes available. From my Bunkers & Badasses: Wonderlands Campaign, this is the amount of scenes I can currently select from to add to a "testing" session note.

![scene-selector1](https://user-images.githubusercontent.com/68425372/194798199-8e9b83ce-f170-406f-87f6-feb7caa0a0cb.png)

Extrapolating this issue to the Testbreaker campaign... and adding quite a few more scenes down the road.

![scene-selector2](https://user-images.githubusercontent.com/68425372/194799495-5aa0af2c-7359-4545-aa1b-c8e76691a27f.png)

## Proposed Solution
I do not know if adding an act filter is feasible, or even smart, as sessions can span across acts. 

Instead, my most basic thinking would be if a session, upon creation, detects that a scene is already marked completed, that it will not show up in this list. 

An even more ideal solution would be an implementation of a date and time completed function alongside the component completion, which would filter out things older than.. 1 month? I don't know how long others wait to write their session notes. :)

**Comment by carlonicora** [comment]
Available in `v3.0.0-1`
