### ISSUE TITLE
Stress Test Results in Assignment of Same Scene Outline Tag

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#157]
During my creation of multiple scenes for my prior ticket, I was creating them sequentially, meaning back to back. 

At **"rpgm/outline/scene/2/4/35/1"** RPGM generated two notes with the same tag and advised correction, which I did. I was able to generate a couple more, but now at **"rpgm/outline/scene/2/4/42/1"** I am hitting a string of them all being generated at the same tag. 

Attached is a screenshot and console log.

![SCR-20221009-wz6](https://user-images.githubusercontent.com/68425372/194800446-28a15bdb-40cd-41e4-95fe-921e549e4380.png)

[obsidian.md-1665376977414.log](https://github.com/carlonicora/obsidian-rpg-manager/files/9743398/obsidian.md-1665376977414.log)

**Comment by carlonicora** [comment]
related to #153 
If the parent is missing, the system can't find the hierarchy

**Comment by carlonicora** [comment]
After fixing #153 I am not able to reproduce this any longer

**Comment by carlonicora** [comment]
Available in `v3.0.0-1`
