### ISSUE TITLE
Inconsistent scene creation behavior

### ISSUE THREAD

**Issue by x1101** [carlonicora/obsidian-rpg-manager#158]
When on an "Act" page, trying to create a new "Scene", using the different methods to invoke this yields different results.

Here's the frontmatter of the Act in question
```
---
alias: []
tags:
  - rpgm/act/1/7/1
completed: true
synopsis: ""
---
```

When using the RPGManager right hand pop-out, the scene is created as expected. 
When using the command pallet (either from the left hand bar or keyboard shortcut) triggering the "Create New Scene" command, the following error occurs:

> Acts missing
> The Obsidian Vault does not contain a RPG Manager Act for the selected adventure. Before creating a scene, please initialize your first act for the adventure 

All Component Tags are set with default values, and "Automatically organize elements in folders" is enabled. 

When the scene is created using the right hand pop-out, it gets front matter like this
```
---
alias: []
tags:
  - rpgm/scene/1/7/1/5
completed: false
synopsis: ""
date: 
times:
  start: 
  end: 
---
```

Obsidian Version: v0.15.9
RPGM Version: 2.0.3
OS: Windows 10 / Fedora Linux / Android

**Comment by carlonicora** [comment]
@x1101  Thanks for the report.

Quick question: when you create the Scene from the Obsidian Command, do you select the correct Campaign and Adventure? Do they fill correctly in the modal as in the screenshot below?

![Screenshot 2022-10-10 at 15 39 59](https://user-images.githubusercontent.com/63145/194879557-0654325d-bed8-4131-8e0e-9d5d042fe42a.jpg)

Could you please attach a similar screenshot, plus the frontmatter of:
1. The campaign
2. The Adventure
3. The Act

of the Scene you are trying to create?

Thanks

**Comment by x1101** [comment]
When I try to use the command pallet to crate a scene, that modal doesn't pop up at all. 

Campaign:
```
---
alias: []
tags:
  - rpgm/campaign/1
completed: false
synopsis: 
settings: Agnostic
dates:
  current: 
---
```

Adventure:
```
---
alias: []
tags:
  - rpgm/adventure/1/7
completed: true
synopsis: "With [[Gibris Darath]] defeated, the threat begins to take shape, and pieces come together"
---
```

Act:
```
---
alias: []
tags:
  - rpgm/act/1/7/1
completed: true
synopsis: 
---
```

I've also confirmed that this happens on _any_ Act in my campaign. (Note, only one Adventure currently has Acts setup)

**Comment by carlonicora** [comment]
@x1101 **NO MODAL????**

Mumble, I have never seen this behaviour. The command is linked to a modal. Would you be able to do a quick video screen capture? Maybe we are talking about two different things at this point :S
