### ISSUE TITLE
[Docu]: Add test vault to GitHub

### ISSUE THREAD

**Issue by carlonicora** [carlonicora/obsidian-rpg-manager#169]
## Scope

Add a test vault to GitHub to show how the plugin works in real life.

### Summary

In order to simplify new user adoption and to lower the entry gap, I propose to add an Obsidian Test Campaign to GitHub. This would give new users the possibility to explore RPG Manager functionality with an up-to date example.

**Comment by carlonicora** [comment]
@sigrunixia I have one campaign with one adventure I used multiple times as a "_scapegoat_". I can easily adapt it to `v3.0` and upload it, but I agree that we need some volunteers for this one.

The campaigns I am running are ~2 years long, so the only one I have in Obsidian are only partial campaigns. As my players do not normally follow the Obsidian tread, I can put together my next one (_Vampire_) and publish it.

### Alternative solutions

Instead of uploading the vaults directly in RPG Manager, we could ask people to upload their campaigns (_our as well_) in a separate GitHub we can link in our documentation/README

**Comment by sigrunixia** [comment]
While working on #196 and further modules out of it, I will be doing it on a clean, RPGM only vault using a "known" story and characters. With luck, it will end up being a good test vault when all is said and done. :)

**Comment by sigrunixia** [comment]
Current [Lord of the Rings](https://github.com/sigrunixia/Othering-And-Arts/tree/main/WIP-Beginner/0%20Lord%20of%20the%20Rings) Test Vault being developed alongside documentation. 

I start adding Elements tomorrow.

**Comment by sigrunixia** [comment]
For the [LOTR Vault](https://github.com/sigrunixia/Obsidian-RPG-Manager-LOTR-Vault) - this is currently in ongoing development, but is still fleshed out "enough" that someone can get a feel for RPG-Manager with it. Spouse and I are planning a marathon video watching to add.. a bunch of things to it next weekend, and I have added some book stuff where it made sense. 

Any other vaults we want to add as test vaults?

**Comment by sigrunixia** [comment]
Moving this back to to-do, because the rewrite will change how this is completed.
