### ISSUE TITLE
Suggestion: "Parties" for multiple group campaigns

### ISSUE THREAD

**Issue by thegiftofgabes** [carlonicora/obsidian-rpg-manager#17]
Whether there is a dynamic world where multiple game groups meet, or you use the same campaign for multiple groups, I would say that there could be a "Party" element where we assign PCs into.

Currently, I am using the Faction element but I guess a dedicated element for that would be useful.

**Comment by carlonicora** [comment]
@thegiftofgabes what would be the difference between a "party" and a Faction?
I use factions for that, calling a faction "_Party_".

Are there different information you would like to show in the party?

My resistance is that I would use it once or twice per campaign

**Comment by thegiftofgabes** [comment]
to be fair, I am not sure if there is a big difference in info, so I'd say I will get back to this later on *if* I find a HUGE difference.

**Comment by carlonicora** [comment]
@thegiftofgabes I will close this for now. Keep it into consideration and keep me posted!
