### ISSUE TITLE
Design Pass

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#174]
## Scope
This is a meta ticket that will act as a reference for other tickets and direct implementation work on RPGM's next major design Pass.

## Purpose
Assist in "taking a step back" planning of design as development of the core features needs to have an idea of functional design in mind. [Obsidian](https://obsidian.md) handles the aesthetic components, but it is our job here to ensure that as soon as the code renders into something, that we make it work great and look awesome. 

### Definitions
1. Templates - An expression of one or more components. This is the outward most most users will see in RPGM. It is sometimes referred to as shell, theme, or overlay. 
2. Component - A container of data that has been given a name and a purpose. One or more of these may be found in a code block, which is then rendered in a template. 
3. Code Block (or Codeblock) -  A specific marked off area of text that tells a program to treat this area differently than the rest. In  Obsidian, Code Blocks are marked by the introduction of three grave symbols (```) and a pre-defined label, followed by the desired text, and exited by three more grave symbols
4. Core Feature - A core feature is a function that is available in the RPGM plugin, that is also not reliant on the installation of another plugin or add-on.
5. Design - An expression of form that also contains function. 
6. GUI - Graphical User Interface. Can be pronounced as Goo-eee. When lines of programming text obtains a template or a shell that allows interfacing outside of the command line.
7. Command Line - The basic system for a user to provide external instructions to an operating system. Microsoft DOS, *NIX, the the terminal, SSH shells, are all ways to access the command line.

## Current Status
- #218 

## Currently Related Projects
- #161 
- #167 
- #168 
- #169
- #217 
- #196 

Tasks that do not need their own ticket will be tracked in comments below.

**Comment by sigrunixia** [comment]
## Plugin Philosophies
Here is [Gitlabs Mission and Vision Statement](https://about.gitlab.com/company/mission/) page for reference.
- [ ] Obtain a 1-2 Sentence blurb Plugin Mission Statement
- [ ] Obtain a list of 3-5 Goals the Core Plugin is Meant to Accomplish
- [ ] Obtain a very conservative wishlist of what the plugin will look like in 3, 6, 9, and 12 months. 

There is no current due date for these tasks.

### Purpose
Having a very clear idea the current boundaries of "who" the plugin is, what it is meant to do, where it is meant to go, why it is doing what it is doing, and how it is going to accomplish it. Since it is software we do not address the when. 

These are not hard boundaries, in that they can change. In the meantime, it help any developers, collaborators, testers, and users keep on track and keep within the spirit of what the goal of the RPGM is; the project manager without the micromanaging. :)

**Comment by carlonicora** [comment]
...wip...

## Vision, Mission and Values

### Vision

A tool to simplify the plot, run and track of role playing game campaigns.

### Mission Statement

Help storytellers to be plot better campaigns in less time

### Values

- Simplicity
- Automation

**Comment by sigrunixia** [comment]
Before we get too far forward, I want to make sure we get a little further in the "Vision, Mission and Values."

I promise I am not being pedantic. We'll start large and then condense down. 

## Vision
"A tool to simplify the plot, run and track of role playing game campaigns."
- Simplify how?

## Mission Statement
Help storytellers to be plot better campaigns in less time

- For the _record_, define plot.
- Less time, or maybe with less friction? Less mental overhead? 

## Values
- Simplicity
- Automation

---

Are simplicity and values really the top? Not something about bringing people together through storytelling?

**Comment by sigrunixia** [comment]
I am going to close this up as we're overhauling everything, anyway. :)
