### ISSUE TITLE
Character pictures get lost in the milieu and need option for multiple pictures

### ISSUE THREAD

**Issue by lazarusomega2000** [carlonicora/obsidian-rpg-manager#187]
Two issues have come to my attention with your system:

1. I'm used to organizing my pics into categories so I can find them easier. When I add a sub-folder for NPCs in my assets library and transfer my NPC pics there, this system loses the pictures and can't display them with the character anymore. #185 
2. I have several shapeshifter characters that need separate pictures for their "forms". In its present form, the system will only let me do that if I use a photo-editing system to combine those pics into one.

Thanks for all your hard work! I treally love the system so far!

**Comment by carlonicora** [comment]
Hi @lazarusomega2000 

Thanks a lot for your thoughts and request.

I have one important question for you... If you were to have multiple images for the same character, how would you like to see them displayed?

### Proposed Solution

I would propose two different ways for this.
1. Replace the current image with a component that, in case of multiple images, will show one of the image with some navigator links below it, with the possibility to switch from one image to the next. (Ideally the images should cycle every few seconds)
2. Add a sort of gallery at the bottom of the component if multiple images are present in the system

Any comments of thought on this (@sigrunixia as well)

**Comment by sigrunixia** [comment]
## Suggested addition
Option 3: Button or link for next/prior image. 

However, I am leaning into option 2.

## Implementation
**Attachments Method**
The Gnome named Pie has three images that are thrown into the chosen image-attachments folder. RPGM will read them in this order.
`pie.jpg is the primary image`
`pie2.png is the secondary image`
`pie3.gif is the tertiary image`

**Link Methods**
I am stumped for the internal and external image linking methods...

**Comment by carlonicora** [comment]
@sigrunixia I would say that we can add all 3 options. Your point is added to my first one.

**Comment by lazarusomega2000** [comment]
I agree. All of those options would work wonders for me. Maybe include a
setting to turn off options that you don't want.

**Comment by carlonicora** [comment]
@lazarusomega2000 check `v3.1` for the multiple image support! :)
