### ISSUE TITLE
Query on Javascript Wrapping

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#189]
## Scope

Determining if it is possible in the future to wrap [Obsidian-5e-Statblocks](https://github.com/valentine195/obsidian-5e-statblocks#accessing-the-bestiary).

### Current Actions

Currently, Statblocks are manually placed in a free section on any element or component, and left where it is placed.

### Suggested Actions

If a Obsidian-5e-statblock is placed on a note that is tagged as a RPGM note, the stat block is captured and moved up with the remainder of the component blocks. 
This can be overridden with a true/false YAML setting in RPGMdatamanager.

### Possible Solutions or Implementations

From the readme of Obsidian-5e-Statblocks:
```
Accessing the Bestiary

Your bestiary lives on the plugin and can be accessed programmatically in plugins that can run JavaScript, such as [Dataview](https://github.com/blacksmithgu/obsidian-dataview), [Templater](https://github.com/SilentVoid13/Templater) or [CustomJS](https://github.com/samlewis0602/obsidian-custom-js).

A readonly copy of the bestiary is available on the window object and can be accessed in your scripts like this:

const bestiary = app.plugins.getPlugin("obsidian-5e-statblocks").bestiary;
//or
const bestiary = window.bestiary;
This will give you a readonly JavaScript [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map).

Creatures are stored on the Bestiary by name - you could retrieve a creature from the bestiary like this:

const ancient_black_dragon = bestiary.get("Ancient Black Dragon");
Or, a list of all creatures:

const creatures = bestiary.values();
```

## Context or Use Case
 

 
I was thinking about what functionality would be missing with an entities template, and what would users still be looking for. 5e-Statblocks does its job real well, its custom templates can ultimately work for any style, and its only major qualm is right now the dev is busy so any major tinkering is done with pull commits.

---

_Originally posted by @sigrunixia in https://github.com/carlonicora/obsidian-rpg-manager/issues/161#issuecomment-1278325451_

**Comment by carlonicora** [comment]
@sigrunixia I have finally looked at the integration with statblock, and while it is doable, there are certain limitations.

I cannot hijack a codeblock/statblock and move it inside the header, as the statblock is processed by its plugin. However, what I can do is to allow a new RpgManagerData key to use the statblock database.

However, I have the feeling we are discussing something similar to #161, which I haven't wrapped my head around just yet.

...to be discussed...

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
