### ISSUE TITLE
Theme Song/Playlist Spot

### ISSUE THREAD

**Issue by thegiftofgabes** [carlonicora/obsidian-rpg-manager#19]
Adding a place to slap in a song or playlist link would be great for those characters we like to add theme songs for.

**Comment by carlonicora** [comment]
@thegiftofgabes this is a **very** good idea.
Do you think the songs/playlists should be linked to scenes?

Also, it is enough to have an element "_Song_" or both "_Song_" and "_Playlist_"?

**Comment by carlonicora** [comment]
Playlist:
- list of songs

Song:
- link (url)

**Comment by thegiftofgabes** [comment]
I would say that both playlist and song should accept links, because I could build the playlist on spotify or yt or whatever, and share the playlist link, instead of individual songs. but if you have individual songs.

I guess most elements can be improved with music: characters, adventures, scenes, and sessions.

Theme music helps with vibes for characters, dynamics of scenes and sessions, atmosphere for an adventure or campaign, locations, etc...

Perhaps, the higher level elements, such as campaign and adventure could list all songs and playlists from the elements below, so adding a couple songs for a location or session shows in an adventure or session they are related to, instantly creating playlists of sorts...

I don't know, the possibilities are many!

**Comment by carlonicora** [comment]
Instead of having "_Song_" and "_Playlist_" I would create an element called "**Music**". Music can be both, music can list other music through relationships, and have its own URL. I think that would make things simpler!

**Comment by thegiftofgabes** [comment]
oh yeah! how come I didn't think of it!

**Comment by carlonicora** [comment]
Released in [v1.2.0](https://github.com/carlonicora/obsidian-rpg-manager/releases/tag/1.2.0)
