### ISSUE TITLE
Allow reordering scenes in Act and Sessions

### ISSUE THREAD

**Issue by carlonicora** [carlonicora/obsidian-rpg-manager#192]
## Scope

The scenes are locked in their position in an act or a scene when they are created.

### Current Actions

Moving scenes up and down an act is complicated, and impossible to do in a session

### Suggested Actions

Allow users to define the positioning of a scene in an act or a session

#### UI

Allow users to move scenes up and down in the list in an Act or a Session. Ideally having a drag-and-drop style if supported by Javascript **without** the addition of jQuery

#### Backend

Add a new function in `CodeBlockManipulator` class to allow multiple components at the same time, update the positioning, save them all in one go and only after that refreshing the database

## Context or Use Case

<As a> User
<I want to> decide the position of the scenes in an act or session even after the scene creation
<so that> I can reorder them the way they make sense

## Related Issues

#190 
#191

**Comment by sigrunixia** [comment]
Can confirm it works on 3.2.05.

Added to documentation queue.

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
