### ISSUE TITLE
[Wrap-Up] Documentation - Beginners Guide

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#196]
**Current Stage**: Wrap-Up

## Final Tasks
- [x] Finalizing Layouts, Generating Pictures (pictures take a while)
- [x] Navigation link up top and bottom due to Github
- [x] Add to Wiki
- [x] Check by x1101 and carlonicora 
- [x] Revisions
- [x] Second Check by x1101 and carlonicora
- [x] Publish

**Comment by sigrunixia** [comment]
- [ ] Once campaign setting is removed, get new screenshot of "Create a Campaign"

**Comment by sigrunixia** [comment]
This is "essentially" done except for some smidges of touches and some fresh screenshots I need to take due to recent changes.


Check it out here: https://github.com/carlonicora/obsidian-rpg-manager/wiki/Beginner's-Guide

**Comment by Z3DT** [comment]
Is the Beginner's Guide outdated, or is my RPGM version outdated? When creating a new Campaign, the screen looks different. It does not let me set a date or choose a system, only enter a name and choose a template.

I installed RPGM from the community plugin screen. I'm running RPGM 3.4.5 on Obsidian 1.2.4 (updated literally minutes before posting this)
