### ISSUE TITLE
Date picker picks day before

### ISSUE THREAD

**Issue by mykelalvis** [carlonicora/obsidian-rpg-manager#203]
I just started testing rpg manager, and noticed that when I picked the date on the campaign page it selects the day before the one I picked in the picker.

Starting date as the 11th
<img width="674" alt="image" src="https://user-images.githubusercontent.com/104666/196182964-ad3d5787-12f8-488e-8773-95216974ffa5.png">
When I pick the 9th
<img width="550" alt="image" src="https://user-images.githubusercontent.com/104666/196183470-861e9ca7-4cfe-40c6-8988-583bb2009283.png">
it sets the date to the 8th
<img width="392" alt="image" src="https://user-images.githubusercontent.com/104666/196183178-51f8fc01-53e5-4027-92e9-d23f6ee89133.png">

**Comment by carlonicora** [comment]
Hi @mykelalvis 

This has been fixed in #201  and will be released soon
