### ISSUE TITLE
How to Add an Image

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#210]
Apologies for the lack of fancy template :)

This is the ticket to Re-Add the ability to add a banner image back into the campaign hierarchy page by default. I am not sure if you can tie it into the gallery image manager or not, but there you go.

**Comment by carlonicora** [comment]
@sigrunixia can you tell me more about this? I did not understand it. Is it about the Campaign Banner Image?

**Comment by sigrunixia** [comment]
Ah yes, it is! It was technically hidden/lost when you changed the image/images YAML. 

I'm just suggesting you add gallery support to the campaign page.

**Comment by carlonicora** [comment]
Done, ready for release

**Comment by carlonicora** [comment]
PS: you know that now users will ask us to organise the images so that they can pick the one they want in the cover, right? :D

**Comment by sigrunixia** [comment]
Hahaha. They can select one themselves.
