### ISSUE TITLE
New Create a Campaign Date did not Preserve on New Campaign Screen

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#212]
## Scope

Campaign Creation

## To Reproduce

Create a campaign and put any date in the Campaign date field while selecting campaign type, template, and so on. I used the following settings in the screenshot below. 

## Expected Behavior

I expected The Campaign to generate with the date in the "Current Date Box."

## Screenshots
![RPGM_Campaign_New_Fill_Window](https://user-images.githubusercontent.com/68425372/197069647-2bf3d595-fba1-4266-b35c-20fca488903a.png)

## Desktop (please complete the following information)
OSX Monteray
Obsidian 1.0

**Comment by carlonicora** [comment]
I have temporarily removed the option.

The system is ready to collect `component` (`element`) specific information, but it is a hidden feature which needs some more work.

Removing it will remove some uncertainty for the users and we can put it back when ready!
