### ISSUE TITLE
Clarification on Current Campaign Settings

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#213]
It looks like the current documentation available is missing the differences between Agnostic, Raw, and Vampire.

Can I get a 1 sentence summary of what each of them are?

**Comment by carlonicora** [comment]
"A mess" :)

Jokes aside, the main aim of RPG Manager is to offer a plugin that agnostically supports any possible setting. Some settings will have some specialised view.

At the moment we do not have any specialised view for any additional game settings.

Shall we remove it for now?

**Comment by sigrunixia** [comment]
If it does nothing functional, then yes lets remove it for now until it changes something. :)
