### ISSUE TITLE
Campaign Completed

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#214]
May I have some clarification on exactly what happens to all the components when a CAMPAIGN is marked as completed? Does automatically mark all its child components as completed? Simply lock the page from editing...?

**Comment by carlonicora** [comment]
@sigrunixia The `completed` only means that I have finished writing a `component`. It is just a checkbox that says "_I have written what I needed and I am happy with the content_". It does not trickle down in any way

**Comment by sigrunixia** [comment]
Wow, and all this time I took it as written and thought you waited until the end of the campaign to mark this one completed. Whoops. On Oct 21, 2022, at 04:20, Carlo Nicora ***@***.***> wrote:﻿
@sigrunixia The completed only means that I have finished writing a component. It is just a checkbox that says "I have written what I needed and I am happy with the content". It does not trickle down in any way
