### ISSUE TITLE
Can't delete items from relationships?[BUG]

### ISSUE THREAD

**Issue by Delphidex** [carlonicora/obsidian-rpg-manager#219]
## Scope

Unchecking a pre-existing relationship in the Manage Relationship wizard does not remove the relationship.  Once an item is added, it can not be removed.

### To Reproduce

Steps to reproduce the behaviour:
1. Go to 'Clue'
2. Click on 'Manage Relationship'
3. Select "Location"
4. Add an existing location
5. Close Relationship Wizard
6. Click again on 'Manage Relationsihp"
7. Unselect an "Existing Relationship"
8. Close Relationship Wizard
9. See error - Location is still listed under Locations area

### Expected behaviour

Unchecking an existing relationship would remove it from the relationship list

### Desktop (please complete the following information)

 - OS: Win 10
 - Browser Chrome
 - Version Version 107.0.5304.62 (Official Build) (64-bit)

### Additional context
I have also tried to follow the directions posted on the tutorial videos hoping I could over-ride it manually.  Deleting the text in the source code does not work - the code keeps repopulating.  I realize the tutorial is for an older version, but hoped it would work! I apologize if this is something I am doing wrong - I am just starting to use your plug-in, but I wasn't able to find alternate info, and it seems like it should work as expected.

**Comment by carlonicora** [comment]
Hi @Delphidex 

Thanks for your report. I tested it and it is working on my side, but I am running a new version which may have a couple of fixes.
Before investigating further, can you please make sure the Location is not linked in your Note through a normal Obsidian Link? That's the only thing I can think right now.

If you have a link in the text of your note, you cannot remove the relationship, as that is defined in your text.

PS: would you be able to open the RpgManagerData codeblock and copy/paste it here? You can open the codeblock by clicking on the dice icon in your Clue.

Please do let me know and I will investigate further.

Carlo

**Comment by carlonicora** [comment]
@Delphidex also, something you can try is to reload Obsidian. To do so, open the Command and select "_Reload app without saving_"

**Comment by Delphidex** [comment]
No links from previous.  I created the Clues and Locations using the "New X" function in RPG Manager.   

Here is the source code for the Garage, which contains the Corpse clue added with the Manage Interface:
```RpgManagerData
data: 
  synopsis: 
  complete: false
  address: 
relationships: 
  - type: "bidirectional"
    path: "Clues/Corpse.md"
    description: 
```

1. If I remove the check mark, the item is still displayed in the component list.  If I go to the  "</>" section next to Corpse in the list, I still see this:
```RpgManagerData
data: 
  synopsis: 
  complete: false
  address: 
relationships: []
relationships:
  - type: unidirectional
    path: Clues/Corpse.md
    description: 
```
2.  Closing and re-opening the note still shows the Corpse in the list.
3. Exiting and starting Obsidian entirely does remove it from the list.

Is there a way to force a refresh of the code short of exiting the application?  I would assume this is not the expected function or what you are seeing!

**Comment by Delphidex** [comment]
> @Delphidex also, something you can try is to reload Obsidian. To do so, open the Command and select "_Reload app without saving_"

That will resolve the issue for me.  However, I am guessing this is not desired behavior.  However, thanks for the workaround as it will keep me going.  Also thanks so much for your work on this - it is really great.  I am loving testing this out and seeing how I can make this work for my gaming.  Much appreciation.

**Comment by carlonicora** [comment]
@Delphidex there is something hanging in the cache... Sorry for that.
Next week `v3.2` should be released, and as I don't have this issue at all (_I am running a beta of `v3.2`_) this will be automatically sorted there.

Sorry for the hiccup, things will be sorted soon! (**and thanks for using RPG Manager**)

**Comment by carlonicora** [comment]
Bug fixed and ready to be released in next version
