### ISSUE TITLE
Include Explanations of Story Models within RPGM

### ISSUE THREAD

**Issue by lazarusomega2000** [carlonicora/obsidian-rpg-manager#220]
Provide reference to the Story Structures you are referring to within RPGM (ABT/Story Circle) so that the information is readily accessible without referring back to your dev notes in git. I find myself having to refer back to the story cycle and ABT reference material quite often in order to use the system well.

I feel like you could either include a note that explains them which can be referenced by your template or you could make some sort of popover reference material that is visible on mouse-over.

**Comment by lazarusomega2000** [comment]
A separate but more interesting idea would be to include a way to add more story structures, so someone could customize that format for their own style.

**Comment by sigrunixia** [comment]
## From a documentation standpoint

The creation of a "Mini" guide within RPGM I think is doable on my end. A limited to a 1-2 sentence per term glossary. However, it is not a community norm as far as plugins go. It does not mean it should not be explored. 

A second factor is that I am building the existing guides in such a way that they can be downloaded as a vault in and of themselves. Meaning right now, you could clone the development repo, open it in its own obsidian vault, and everything is ready to go, and update it as it receives updates. This is in addition to what will be available online on the official Github when its closer to being done.

## Additional Story Structures

This is more a Carlo question. I see this as being something that would need, at the minimum, to be a plugin integrated into RPGM-Core. It would also have to have some severe limitations. 

Can you provide examples of what structures you would like to see, ideally in a graph form?
