### ISSUE TITLE
UI/Color Coding Scenes According to Story Structure

### ISSUE THREAD

**Issue by lazarusomega2000** [carlonicora/obsidian-rpg-manager#221]
Right now it is difficult to determine, at a glance, what story structure stage any given scene is at relative to its parent Act/Adventure. 

I have seen several Add Ons for Obsidian that can change the colors of file as they appear in the Obsidian File Manager. I think something similar to that would be helpful in the file manager. It would also be good to have the RPGM outlines be the same color so that you could see it at a glance when you are looking at the file.

**Comment by sigrunixia** [comment]
Can you do a quick mock-up in paint or another program of what you would like to see? 

I have a few ideas, and it may already be possible, but want to make sure.

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
