### ISSUE TITLE
how do I manually activate the template updater?

### ISSUE THREAD

**Issue by StarSword-C** [carlonicora/obsidian-rpg-manager#224]
Just updated from the last 2.## to 3.1. I had the pop-up dialog come up to update my campaign vault's files to the new file structure, but I accidentally closed the window while I was making a backup of the old version and now I can't figure out where the option is to run the file updater manually.

Already looked in the documentation but I couldn't find it.

**Comment by sigrunixia** [comment]
If you disable RPGM, restart Obsidian, and re-enable RPG Manager, it should prompt you to update the vault. 

If it doesn't, try this.

Go to `.obsidian/plugins/RPG-Manager/`

Open `data.json`

Look for the key `"previousVersion": "x.x",`

If it says 3.1, change that to be your last prior 2.x.x version. You can reference the [Releases](https://github.com/carlonicora/obsidian-rpg-manager/releases) page help determine when you last updated.

**Comment by StarSword-C** [comment]
> If you disable RPGM, restart Obsidian, and re-enable RPG Manager, it should prompt you to update the vault.

Thank you, this solved the initial problem. Several of my components threw an issue saying they're missing a campaign with an id of 1, but I was able to fix that by manually going through them and then reopening the vault again. Also, and I don't know if this is something you guys had anything to do with, the dates coded in some components didn't change over the new order (was MM-DD-YYYY, is now YYYY-MM-DD).

**Comment by StarSword-C** [comment]
Also, something else odd I noticed: in a couple of places, data that was in the "goals" field of an NPC got moved to the "pronoun" field for some reason. I'll attach examples.
[Queen Natali Cervi OLD.md](https://github.com/carlonicora/obsidian-rpg-manager/files/9925701/Queen.Natali.Cervi.OLD.md)
[Queen Natali Cervi NEW.md](https://github.com/carlonicora/obsidian-rpg-manager/files/9925707/Queen.Natali.Cervi.NEW.md)

**Comment by carlonicora** [comment]
@StarSword-C ouch, that's very strange. I will dig into it to see what went wrong.
In regards to the dates, RPG Manager currently supports Gregorian calendar, so it is feeding the date to the date manager, that probably went haywire with the date you are using. 

Soon RPG Manager will support Fantasy Calendar...

**Comment by StarSword-C** [comment]
> @StarSword-C ouch, that's very strange. I will dig into it to see what went wrong. In regards to the dates, RPG Manager currently supports Gregorian calendar, so it is feeding the date to the date manager, that probably went haywire with the date you are using.
> 
> Soon RPG Manager will support Fantasy Calendar...

Well, Pathfinder actually uses the Gregorian calendar, just with different month names and with the years starting in the 48th century, but yeah, in the last version of RPG Manager those dates did work.

**Comment by cjolson** [comment]
> Also, something else odd I noticed: in a couple of places, data that was in the "goals" field of an NPC got moved to the "pronoun" field for some reason. I'll attach examples.
> [Queen Natali Cervi OLD.md](https://github.com/carlonicora/obsidian-rpg-manager/files/9925701/Queen.Natali.Cervi.OLD.md)
> [Queen Natali Cervi NEW.md](https://github.com/carlonicora/obsidian-rpg-manager/files/9925707/Queen.Natali.Cervi.NEW.md)

This actually happened with me too! Though I think it was moving `dob` to the `goals` on for some files. It was kinda inconsistent. I fixed them too, so I don’t have any examples handy.

**Comment by carlonicora** [comment]
@cjolson 
Yes, I have found the bug for the goals and fixed it already, it will be out in the next version, alas for the previous import... :(
