### ISSUE TITLE
How to improve the Clues

### ISSUE THREAD

**Issue by carlonicora** [carlonicora/obsidian-rpg-manager#226]
## Scope

The chain `event`/`clues` is easy to get lost in the current implementation. Clues are the cornerstone of investigative campaigns, but they are challenging to manage and they are elements which do not simplify a storyteller's life.

The current issue is that they are standalone, and they do not help the storyteller create a chain of possibilities that lead to the clues.

### Describe the solution you'd like

In an ideal world, while plotting a campaign, the storyteller should lead the player characters to a specific clue. The clue should then provide an information to the player characters. In the Alexandrian, the [three clue rule](https://thealexandrian.net/wordpress/1118/roleplaying-games/three-clue-rule) the idea is that the clues should lead to an information. At the moment RPG Manager uses clues as the information, but does not help to plot how the player characters can get to the clue. So, the first issue is that the clue in RPG Manager are actually information.
Semantics aside, and back to the point, at the moment the structure required the storyteller to identify the clue and then position the clue itself in a plot, without any help.

**What if...** RPG Manager were to ask the storyteller:
1. What is the clue you want the player characters to find? (_identify the information_)
2. Who knows about the clue? (_identify the non-player characters involved_)
3. Where can the clue be found? (_identify the locations where the information can be found_)
4. Are there any clue that can lead to the clue? (_identify alternative information that can lead to the main information_)

So, the goal is to trace multiple paths that might lead to a specific clue in a simple way, with RPG Manager asking question to reach the goal of allowing the player characters to find the clue. **The main objective is NOT to create a clue, but to create the trail to find the clue**. This is the complicated part, not the creation of the clue itself, that is trivial.

These `paths` are an `element` on their own, they are a way to reach a `clue`. They have two separate parts to them:
1. Creation of the `paths`
2. Integration with the plot.

### Path creation

- I create a new clue
   - RPG Manager asks me who knows about the clue
   - RPG Manager asks me where the clue can be found
   - RPG Manager asks me if there are any clue that may lead to the non-player characters or the location (this is another clue, and the story repeats itself)

This circle should create the `paths`

### Path integration in the plot

Where do the clues come into play in an ABT/Story Circle plot? They are highly likely used in the second act ("_AND_" in the ABT Plot and "_Go/Search_" in the Story Circle plot). They may also be used in the later stage of the third act ("_BUT_" and "_Take_"). 

More than an integration, the use of `paths` should be the driving force behind the creation of the plots themselves. Let's consider an ABT plot. 
1. Make the player characters feel a NEED
2. Plot what they can do to reach the PERCEIVED GOAL
3. Make them pay a big price and realise the REAL GOAL
4. TRIUMPH

To simplify its creation, the questions should be:
1. What is the perceived goal of the adventure/act? (_identify what the player characters think they need_)
5. What is the true goal of the adventure? (_identify the resolution_)
6. How do they feel they need it? (_identify the need_)
7. What is the clue to lead them there? (_identify the clue_)
8. What happen when they reach perceived goal of the adventure? (_how to touch the lowest part and identify the true goal_)
9. What is the clue to lead them to the real need? (_identify the clue_)
10. How will they win the adventure? (_finale_)

The `clue` is transformed from a mere object to the driving force behind the creation of the plot, with the `paths` to be used in order to simplify the creation of the plot itself.

Let's say that I have created the structure through the help of the clues and RPG Manager helped me create the `paths`. RPG Manager can now help me link the paths to the plot.

## A possible "Wizard Style" Plot creation

Let's consider the following steps as part of a "Guided Plot Creation", a sort of "Wizard Creator" for the plot:

1. What is the current reality of the player characters? (_You_)
2. What is the end goal of the adventure/act, the TRUE goal the player characters will TRIUMPH achieving? (_Return_)
3. But what is the perceived goal of the adventure/act, the thing that they think they need? (_Go_)
4. What is the clue to make them feel the need? (and its paths) (_Need_)
5. When they decide to start looking for the perceived goal, what is the clue that will lead them there? (and its paths) (_Search_)
6. When they find what they think they need, what is the price they pay? (_Find_)
7. When they pay the price, what is the clue that will lead them to the TRUE goal? (and its paths) (_Take_)
8. How are they going to triumph (_Change_)

A structure like this will mimic the Story Circle, but simplifying its creation, while at the same time creating the story elements in a simple, yet consistent way.

The Story Circle plot may be rewritten in the following form:
1. Introduction (You)
2. Paths to need (Need)
3. Acceptance of adventure (Go)
4. Paths to perceived goal (Search)
5. Find of the perceived goal and payment of the price (Find)
6. Paths to true goal (Take)
10. Acceptance of the new life (Return)
11. Triumph (Change)

## Questions

- Does this make sense?
- How can we call the `paths` to lead the player characters to a `clue`?

## Data Structure for Nerds

- Adventures/Acts contain Plot Elements
- Plot Elements contain Paths and Scenes or Acts
- Scenes or Acts may contain Paths
- Paths lead to Clues
- Clues lead to Decisions

**Comment by carlonicora** [comment]
## Plot Wizard Idea

for this example I will use a set of names I used in a Cyberpunk campaign, changing the plot in order to make it easier to understand.

### Step 1: The player characters - _YOU_

- Text to identify the current reality of the player characters. Where they are in the story and what they have decided to do at the end of the previous session

> The player characters have killed `John D'amico`, but `Hina Matsushito`, who controls the military operations of `KenshaTech` is still at large and waging war against the `Three Wise Monkeys`.

### Step 2: What is the perceived goal of the adventure/act? - _GO_

- Description to identify what the player characters **think** they have to do

> Find where `Hina` is and kill her.

### Step 3: What realisation the player characters have or price do they have to pay when they reach the perceived goal? - _FIND_

- Description to identify what the player characters learns when they reach their perceived goal that will reveal the true goal

> Realise that the `freaks`, children `KenshaTech` was experimenting on are mutants. They are a species on its own, and that the world is not ready to accept them yet.

### Step 4: What is the end goal of the adventure/act? - _CHANGE_

- Description to identify what the player characters will reach once the adventure/act is over.

> Help the `freaks` moving to a safe location, where they can hide from the world.

### Step 5: Why should the player characters feel the need to act? - _NEED_

- Description to identify the reasons to use to push the player characters over the threshold

> When exposed, `Hina` will drop small atomic bombs over London

### Step 6: What is the clue that will lead the player characters to their perceived goal?  - _SEARCH_

- Description to identify how to reach their perceived goal
- Title and Description of the clue
   - List of non-player characters (if any) who have the clue and Description on their relationship with the clue
   - List of locations (if any) where the player characters can find the clue
   - List of events (if any) the player characters can witness that will lead to the clue

> Find where `Hina` is hidden
> _The hiding place of `Hina` (clue)_: Hina is hiding in plain sight in the `Warwick Avenue Underground Station` in London
>  - _`Mark` (non-player character)_: he knows where Hina is hidden
>  - _`Emily` (non-player character)_: she knows where Mark is, and she knows Mark knows how to get to Hina
>  - _`The Black Market for Medicines and Gas Masks` (event)_: The player characters witness a spike in the black market for strange medicines against radioactivity and gas masks. They are paid in cash and to be delivered to `Warwick Avenue Underground Station`

### Step 7: When they pay the price, what is the clue that will lead them to the TRUE goal? - _TAKE_

- Description to identify how to reach their perceived goal
- Title and Description of the clue
   - List of non-player characters (if any) who have the clue and Description on their relationship with the clue
   - List of locations (if any) where the player characters can find the clue
   - List of events (if any) the player characters can witness that will lead to the clue

> The player characters need to find the best place to hide the `freaks`
> _The best place to hide (clue)_: Realise that the best place for the `freaks` to hide is `Barquisimeto` in Venezuela. The place where the `freaks` were created, abandoned by `KenshaTech` and under control of the `Cartel` and the AI `Vee`, who have helped the player characters in the past
>  - _`Lucia` (non-player character)_: She wants to bring her daughter (one of the `Freaks`) home, and the `Cartel` she leads can offer protection for the children
>  - `Aiden` (non-player character)_: Wants to go and meet `Vee` to have a proper conversation with the AI and considers retiring in `Barquisimeto` as it is a solitary area now that the corporations are retiring from there.
>  - `Warwick Avenue Underground Station` (location)_: A tactical map shows how `Hina` has decided to abandon `Barquisimeto` as the opposing Corporation left and `Vee` is making `KenshaTech` life too hard to have an operation there

### Step 8: How are they going to triumph? - _RETURN_

- Description to identify how the player characters are going to reach the true goal of the Adventure/Act

> Take all the `freaks`, `Lucia` and `Aiden` and go to `Barquisimeto` to allow them to start a new life

## How would RPG Manager translate this into a Story Circle Plot?

| Plot Stage | Description |
|---|---|
|**YOU**| The player characters have killed `John D'amico`, but `Hina Matsushito`, who controls the military operations of `KenshaTech` is still at large and waging war against the `Three Wise Monkeys`. |
|**NEED**| When exposed, `Hina` will drop small atomic bombs over London |
|**GO**| Find where `Hina` is and kill her. |
|**SEARCH**| Find where `Hina` is hidden (Find _The best place to hide_ that can be found through _Mark_, _Emily_ or _the black market_)|
|**FIND**| Realise that the `freaks`, children `KenshaTech` was experimenting on are mutants. They are a species on its own, and that the world is not ready to accept them yet. |
|**TAKE**| The player characters need to find the best place to hide the `freaks` (Find _The best place to hide_ through _Lucia_, _Aiden_ or _Warwick Avenue Underground Station_)|
|**CHANGE**|  Help the `freaks` moving to a safe location, where they can hide from the world. |
|**RETURN**| Take all the `freaks`, `Lucia` and `Aiden` and go to `Barquisimeto` to allow them to start a new life |

## Notes

The clues can be reached through paths, that link the clue to non-player characters, events and locations. The paths must be used in two specific part of the Story Circle: **SEARCH** and **TAKE**. The paths are the important element, because RPG Manager should remind the storyteller to place the paths in those specific stages during the creation of the scenes or act.

The structure can be used in both Adventures and Acts, in order to simplify the creation of the children Acts or Scenes.

**Comment by cjolson** [comment]
If it’s helpful, this is how I’ve used Clues so far. I’m currently running a campaign that heavily uses the Alexandrian Three Clue Rule as well. A lot of my clues are notes/handouts/documents the party can find – though there are a few exceptions.

For each Clue, I define:
- What is its source? Where can the players find it or what NPC has it?
  - Normally this is a `Location` or `NPC`.
- Content; in the body of the note I detail the specific descriptions of the clue (what it says, what it looks like, etc).
- What does the clue reveal? What other components can it lead the PCs to discover?
  - These generally include `NPCs`, `Locations`, or “Revelations” (which I use `Subplots` for).

Based on how I set it up, a _parent/child_ relationship would make sense. For me, the hierarchy goes: Source > `Clue` > Learnings: 
- **Source > Clue:**
  - _Source as Parent:_ The `Clue` is linked in the body of the Source note. I often update the description of the clue in the Source note to be more specific about where it is (i.e. “In his pockets.” or “Area A4”)
  - _Clue as Child:_  The `Clue`’s relationship to the source is only linked through the the source/parent note. 
- **Clue > Learning:**
  - _Clue as Parent:_ The body of the `Clue` has a link which points to the learnings (an `NPC`, `Location`, or `Subplot`). I provide a description of that relationship in the `Clue` note that says “Reveals”.
  - _Learning as Child:_ The learning is only linked in the clue/parent note (just like _Clue as Child_). I write the description of relationship to the `Clue` as “Revealed by”
    - And then Learnings may act as a source for even more Clues (particularly if it’s and `NPC` or `Location`).

For my “Sources” I keep a checklist in a `Subplot` note that tracks which sources my players have already cleared or visited. This is just so I can easily identify all the Sources they haven’t encountered yet and I can choose one I might point them toward at the start of a session. 

I haven’t found a particular need to tie clues into the ABT structure (yet). It might be because I’m running the Alexandrian’s Remix of Dragon Heist which comes with a bunch of clues and paths up front though (so I don’t need to plan that many during my game prep).

**Comment by sigrunixia** [comment]
I'll chime in real quick. I'll have more on the weekend but wanted to get some things done today. :) 

So I was using clues as objectives for subplots (and treating subplots as kinda like a quest). Followed with if/then situations or breadcrumbs.

`If X happened, then clue was revealed, else clue did this.`

However, I incorporated what I notated as "Unavoidable" into it. Meaning by a certain points in the story, the clue would trigger and be revealed, whether it was hindsight or direct....

**Clue**: Purple Dragon Scale
**Trigger**: "After the [[Purging of the Knaves]] and the [[Victory of Blades]], the party finds a lone, purple dragon's scale."
**Synopsis** (Hidden until Clue is fully revealed): The Purple Dragon's scale vibrates as sulfur and ozone emanate from it; the holster burns away in a flash. 

 **Revelation**
- Anyone touching or within 8 ft of the scale must pass a DC 25 Charisma check (or equivalent skill) or be struck with a 2d20 Arc Flash. Players hit by Arc Flash will continue to take 1d10 burning damage
- If facing the Purple Dragon Scale, the player must also pass a DC 15 Dexterity check to avoid blindness. 

_At the bottom of the note, underneath RPGManagerID, I made a new heading called "Conditions" and "Leads To" which I embed in the appropriate subplots._

### Conditions of Revelation
- [ ] Allow a Loremaster of Draconology to see the Scale
- [ ] Speak to Diitu after completing [[The Broken Shores]] - Unavoidable
- [ ] Complete all the requirements for [[Raising a Dragon-nation]]

## Leads-To
[[Part of the Hoard]] 
[[Sarkantu, The Arbiter of Fate]]

.
So yeah... I was using it way different.. Oops
