### ISSUE TITLE
Would Like Some Way to Add Descriptive Text to Items in Timeline

### ISSUE THREAD

**Issue by lazarusomega2000** [carlonicora/obsidian-rpg-manager#227]
## Scope

Is your feature request related to a problem? 

This is not a problem, so much as a clarity item. I would like to know what the game circumstances were for a given event or death on the timeline.

### Describe the solution you'd like

Ultimately, something similar to how you can change the description of relationships under a character or faction would be ideal.

**Comment by carlonicora** [comment]
Added `resonOfDeath` to characters if the death is not undefined

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
