### ISSUE TITLE
[BUG] Parent Status Overwritten by Adding Link to Body of the Child Note

### ISSUE THREAD

**Issue by cjolson** [carlonicora/obsidian-rpg-manager#228]
## Scope

For `Locations` that are set up with the parent/child relationship, the parent does not display as a parent if it is linked in the body of the child’s note.

### To Reproduce

1. Create two locations. Assign one as the `child` to the other. 
2. You should see them populate the component codeblock as the `parent/child` relationship (“Inside” and “Contains”).
3. Go to the `child` Location note and add a link to the `parent` in the body of the note. 
4. You will notice the `parent` no longer displays in the component’s codeblock. If you include `unidirectional` relationships in the codeblock it does display, but not as a parent. RPG Manager prioritized the `unidirectional` relationship status over the `parent` relationship status. 
5. If you return to the `parent` note, the `child` does still display as a `child`. (However, when it’s possible there are hiccups longterm. When looking up an example to describe, my parent had reassigned ‘unidirectional’ to all it’s children, but I did not notice this the first time I noticed this issue.)  

### Expected behaviour

I would expect the `parent/child` status of a note to override any other relationships (such as `unidirectional` due to it also being linked in the note).

### Desktop (please complete the following information)

- OS: iOS Ventura 13.0
 - Version: 3.1.0

**Comment by carlonicora** [comment]
Fixed, waiting for v3.2
