### ISSUE TITLE
Move IDs to UUIDs

### ISSUE THREAD

**Issue by carlonicora** [carlonicora/obsidian-rpg-manager#231]
## Scope

Detach the ID from the positioning of a plot element in the parent

### Describe the solution you'd like

Currently the plots use the ID system to both identify themselves as well as identifying their position in their parent's children. The need is to create two separate set of information:
1. Unique ID (UUID) for each element
2. Position in the parent element

Moreover, the identification of the parent should raise up one level, plus the campaign ID. The `Scenes`, for example, should only keep the information about the act id, not which adventure the act belongs to. This means modifying the ID system from the current version, to a version which stores the following info:
- id
- parentId
- campaignId

**Comment by carlonicora** [comment]
## To do

- [ ] Organise Adventure, Act, Scene and Session List by `positionInParent`

**Comment by sigrunixia** [comment]
Can confirm this appears to be working swimmingly in 3.4.05.
