### ISSUE TITLE
3.2 Release Fantasy Calendar Testing

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#232]
## Scope

An overview of the inconsistencies that need to be ironed out in for Fantasy Calendar (FC) and RPG-Manager (RPGM).

### Inconsistency List
- [x] When Fantasy Calendar is disabled, an Obsidian reload is required to revert Campaign Page to prior Calendar handling.
	This applies whether it is disabled as a plugin, or the YAML is removed.
- [x] When Switching the Current Day in FC, an Obsidian Reload is required to update current date in Campaign Page. 
- [x] RPGM still displays FC dates in a YYYY-MM-DD format. It ought to pull current date from FC.
	**Example**: _Krotu 11th, 2875_
- [x] Scenes also require the fc-calendar YAML.
- [x] Session Page date does not display IRL Date. It expects date from FC. 
- [x] Selecting Dates of Birth, Death, Event Dates, are unintuitive if not Impossible currently.

## .8 Alpha Testing

- [x] Date picker is semi transparent and will need more CSS specificity, even on default. 
![See-Through](https://user-images.githubusercontent.com/68425372/200755417-0774a363-9726-426e-9072-7207fa58e5b8.png)
- [x] Date picker does not accept the `Enter` key in the year field in lieu of utilizing the +/- buttons. I assume that is why the buttons are there, but just in case. 
- [x] Date picker pop-out auto exits under the following conditions: Choose a different year, select a different month, take any other action on the date picker. 

### Characters

- [x] It is possible to have the Date of Birth and Date of Death Date Pickers open at once, and they overlap. Similar to clue below, they are impossible to close until you interrupt the rendering of the date picker, either through putting the code blocks in edit, or switching to reader mode.
- [x] Clearing out Date of Death also clears out Date of Birth. 

### Clue

- [x] The only way to close the date picker after deleting a date, is to edit reg-manager code block text or switch to reader mode. Escape, exit, delete, and enter do not work.

### Session

- [x] Default date picker works, but will appear blank after selection until selected again.

**Comment by carlonicora** [comment]
Hello @sigrunixia 

I will add some quick replies to your comments:

_When Fantasy Calendar is disabled, an Obsidian reload is required to revert Campaign Page to prior Calendar handling._

I will look into it. I need to check if FC sends an event I can hook into

_This applies whether it is disabled as a plugin, or the YAML is removed._

Same as above

_When Switching the Current Day in FC, an Obsidian Reload is required to update current date in Campaign Page._

Same as above

_RPGM still displays FC dates in a YYYY-MM-DD format. It ought to pull current date from FC._

Even an FC date is set in YYYY-MM-DD format. Am I missing something here? Or is it just an additional display below the selector?

_Scenes also require the fc-calendar YAML._

Uhm... once the fc-calendar is set in the campaign, that dictates the fc-calendar to use for the entire campaign and sub-elements

_Session Page date does not display IRL Date. It expects date from FC._

Will fix it

_Selecting Dates of Birth, Death, Event Dates, are unintuitive if not Impossible currently._

How would you fix it? FC does not offer a date selector. The only option would be to create my own selector (which is a pain TBH)

**Comment by sigrunixia** [comment]
> RPGM still displays FC dates in a YYYY-MM-DD format. It ought to pull current date from FC.
>
> Even an FC date is set in YYYY-MM-DD format. Am I missing something here? Or is it just an additional display below the selector?

I am not sure if we can get the consistency of the two displays to line up. 
![SCR-20221106-id3](https://user-images.githubusercontent.com/68425372/200190337-5fcdf36d-e5e7-4d22-93f6-043297c31159.png)

Technically it is 2875-11-06 as far as YYYY-MM-DD goes, but as far as how "immersive it is" or how useful it is as a display, it does nothing overall different than what native RPGM did. This is not to knock on you at all, but more to point out the effort that went into it, for then this portion to slip through. If it's not possible to pull the actual month and weekday name per the API and display that, I get that. 

> Scenes also require the fc-calendar YAML.
>
> Uhm... once the fc-calendar is set in the campaign, that dictates the fc-calendar to use for the entire campaign and sub-elements

That is problematic then. If FC-calendar is set in the campaign and is needed for the Hierarchy and Elements, then that constitutes a lot of manual addition and removal. 

**Top of mind partial fix**:
If there was a RPGM settings function that enabled a person to toggle FC-Calendar support, and allows them to define the calendar name on the campaign creation page, then the templates that are generated further hierarchy and element pages can include the `fc-calendar: CALENDAR-Name` in the YAML automagically. It doesn't solve the disable part, but we can suggest solutions for users in those cases. 

> Selecting Dates of Birth, Death, Event Dates, are unintuitive if not Impossible currently.
>
> How would you fix it? FC does not offer a date selector. The only option would be to create my own selector (which is a pain TBH)

I'm trying to think and I am not sure if there is a way that also does not accidentally mess up or create more clutter for non-FC users. Event dates are easy, those can be handled with standard fc-date. But on players/npc's we need two dates, and it's unrealistic to expect two external notes (with FC dates) saying his person was born, this person has died. I will think on it. 

#### Thoughts as I continue to mess around with this between reading and assignments
I am fully comfortable waiting for a more formalized patch between FC and RPGM before release of this select feature, as we'll need to test intercalary days, see how rollovers are handled.. it will take some real world days to see what happens. 

Above all else, I can tell RPGM is faster, and I'd be interested in seeing a version without enabled in it.

**Comment by carlonicora** [comment]
> Scenes also require the fc-calendar YAML.

I think there is a misunderstanding here... Once you set the calendar in the fantasy campaign, you don't need to do anything else any longer. All the dates in the campaign will use the same calendar automatically, so there is no need to change anything anywhere!
Also, consider I cannot add a setting in the RPG Manager Settings, as separate campaigns may need separate fantasy calendars.

> Selecting Dates of Birth, Death, Event Dates, are unintuitive if not Impossible currently.

I will work on something today and see how I can make it easier for the users

> Above all else, I can tell RPGM is faster, and I'd be interested in seeing a version without enabled in it.

Uh... not sure I get this :)

**Comment by carlonicora** [comment]
Almost all the tasks have been implemented/corrected, apart from one which I am still working on...

**Comment by sigrunixia** [comment]
Unfortunately I have some more to add with the .8 Alpha.


### General
Upon loading in, it took three reloads to detect my vault setup. It was trying to reassign ID's before-hand when nothing changed. 
Date picker is semi transparent and will need more CSS specificity, even on default. 
Date picker does not accept the `Enter` key in the year field in lieu of utilizing the +/- buttons. I assume that is why the buttons are there, but just in case. 
Date picker pop-out auto exits under the following conditions: Choose a different year, select a different month, take any other action on the date picker. 

### Characters
It is possible to have the Date of Birth and Date of Death Date Pickers open at once, and they overlap. Similar to clue below, they are impossible to close until you interrupt the rendering of the date picker, either through putting the code blocks in edit, or switching to reader mode.

### Clue
The only way to close the date picker after deleting a date, is to edit reg-manager code block text or switch to reader mode. Escape, exit, delete, and enter do not work.

#### Kudos
In deeply exploring fields I just noticed the ABT/SC relative plots. This has probably been here and I am just now seeing it, but I like it!

**Comment by carlonicora** [comment]
@sigrunixia I have patched all the points you raised and will send you `v3.2.0-9` for testing.

The only thing I did not manage to reproduce was `Clearing out Date of Death also clears out Date of Birth.` I tried various different ways, but did not show to me.
