### ISSUE TITLE
[BUG] Character image doesn't render

### ISSUE THREAD

**Issue by cstby** [carlonicora/obsidian-rpg-manager#237]
## Scope

When an image url is provided to the the gallery manager on the character sheet, the image doesn't render.

### To Reproduce

Steps to reproduce the behaviour:
1.  Create a new NPC
2. Click "Gallery" then "Add Online Image"
3. Provide https://static.wikia.nocookie.net/criticalrole/images/c/c5/Avantika_-_Rammaru.jpg/revision/latest?cb=20200523182510 as the image.
4. Exit the gallery manager back to the character sheet.

### Expected behaviour

The image should render inside the RpgManager block. Instead, only a grey image appears.

### Screenshots
![image](https://user-images.githubusercontent.com/45189177/201485270-530363d2-7bf7-4cdb-81de-8690feaf8aa9.png)
![image](https://user-images.githubusercontent.com/45189177/201485306-e5e24990-7bda-443c-b165-3e3424ffd431.png)

### Additional context
It looks like Rpg Manager is normalizing the image url such that all letters are lowercase. Correcting the url manually in the RpgManagerData block resulted in the expected behavior.

**Comment by carlonicora** [comment]
Hi @cstby 

One of the thing I noticed is that some providers block you downloading the same image multiple times. This means that after a while, Obsidian cannot get the image any longer.

If I open the image you linked in the description, I see the grey image, not the correct one.

Also, if I were you, I would link the file, removing everything else behind it:
https://static.wikia.nocookie.net/criticalrole/images/c/c5/Avantika_-_Rammaru.jpg

Using the image link directly, is it working?
