### ISSUE TITLE
[FEATURE] Create RPG Manager-formatted note from right-clicking a broken link

### ISSUE THREAD

**Issue by StarSword-C** [carlonicora/obsidian-rpg-manager#238]
## Scope
Right now if I want to create a new note with RPG Manager's format, I have to go over to the RPG Manager interface pane and manually type in the name of the page I want to create. I wonder if it would be possible to add the RPG Manager components list to the context menu when you right-click a redlink.

This is not a huge problem, it would just be a QOL improvement.

### Solution
Showing here the current context menu for a redlink (i.e. page that doesn't exist yet, technically it's a dark purple link with current formatting) in my campaign vault.
![image](https://user-images.githubusercontent.com/58320836/201549378-bea40301-f9fe-49da-8b2f-a47a4bd4f2e8.png)
The "Create this file" option would become a dropdown menu containing all current RPG Manager components, kind of like how Google Drive or WinRAR add options to the context menu in Windows Explorer.
![image](https://user-images.githubusercontent.com/58320836/201549623-e78dc846-e4a6-44d9-ae7d-c45821bb4828.png)

Clicking an option in the context menu would create the new page with the selected RPG Manager component formatting at the link target. In this case I think I would classify "Armor of Yamashita Mizuki" as a subplot page.

**Comment by carlonicora** [comment]
Hi @StarSword-C 

I will look into the feasibility of this, trying to understand if Obsidian offers the possibility to interact with its editor.

**Comment by carlonicora** [comment]
@StarSword-C Please check `v3.2.3` and let me know if things are as expected!

**Comment by sigrunixia** [comment]
Leaving this thread open till 2022-11-16 to ensure no other issues crop

**Comment by sigrunixia** [comment]
Documentation complete on my side. Will be published with other beginner documentation.
