### ISSUE TITLE
[BUG] Major Freezing

### ISSUE THREAD

**Issue by jewyswan** [carlonicora/obsidian-rpg-manager#240]
## Scope

When creating a new element, clicking to edit an element, or other such actions, obsidian freezes (completely).

### To Reproduce

1. Enable RPG Manager
2. Create, open, or edit an element
3. See obsidian freeze (completely)

### Expected behavior

No / minimal freezing

### Screenshots

Not applicable

### Desktop (please complete the following information)

 - OS: [Windows 11]
 - Obsidian Version: [ 1.0.3]
 - RPG Manager Version: [3.2.1]

### Additional context
In some cases the freeze fixes itself, in most, it requires an Obsidian restart.

**Comment by carlonicora** [comment]
Updating to 3.2.5, but not being able to reproduce bug
