### ISSUE TITLE
[FEATURE] Ability to define some RPG Manager fields through front matter.

### ISSUE THREAD

**Issue by cjolson** [carlonicora/obsidian-rpg-manager#241]
## Scope

While I know your goal is to move away from frontmatter as the main source for RPG Manager variables, there are some use cases where I need to include the same data I provide to RPG Manager in the frontmatter to be accessed by other plugins (Dataview, Kanban, etc.).

> Having to provide the same data twice – once in frontmatter and once in the RPG Manager wizard – can be redundant and tedious. If RPG Manager could use the frontmatter for a variable if it is provided instead of requiring me to duplicate the value in the RPG Manager wizard, that would be super helpful. 

### Describe the solution you'd like

Ex. If my frontmatter includes a `synopsis` field, RPG Manager populates the wizard's value with my `synopsis` value when I use the `Fill` command on the note so I don't have to bring the data in manually. If frontmatter has no synopsis, leave it as default.

### Alternatives

I have no doubt there are many potential alternatives. 

### Additional context

Specifying the data in the frontmatter would be helpful for components I create using [JSON/CSV Importer plugin](https://github.com/farling42/obsidian-import-json), since I can create many notes using a JSON to fill in the frontmatter. Then I can quickly configure those using `Fill` to add them to RPG Manager.

Related request: #239

**Comment by sigrunixia** [comment]
Beginning to research this.

In an effort to see what solutions are available now, versus what would need to be coordinated via patch, add-on, or alternatives, would you provide a working example of how you would use the information found in a RPGM code block in Dataview, Kanban, and other sources? I.e., show how you currently utilize YAML in these instances. 

The dataview one I am familiar with and how it works, it is Kanban and others that I am not so I want to make sure I explore all avenues and see what can be done.

**Comment by carlonicora** [comment]
My 2 cents on this...

- Storing the information in two different places is complicated, in the sense that poses some risks during reading-writing.
- Allowing the user to decide if to store the data in the frontmatter or in the codeblock opens big issues in configurations: the more info are stored in the config, the more confusion we allow (_and if the settings are lost, there will be hiccups_)
- Storing information in the frontmatter is good for sharing

So, at this moment I don't have a proper solution on how to do it, especially how to decide if to write in the frontmatter or in the codeblock...

Will think about it

**Comment by cjolson** [comment]
I figured it out after writing most of this when I got to the ## Alternative section.

> If I include the RPG Manager code block in my Handlebar template, then the campaign does add the component to the Campaign as if I had created it using the built in commands to create a component. I assumed this wouldn't work. A [new Handlebar template.](https://github.com/carlonicora/obsidian-rpg-manager/files/10014626/Handlebar.Template.-.Music.md) when I update the JSON to include the image path.

Seems a shame to delete my write up, so here's what I wrote until I figured that out: 

---

@sigrunixia Here are a more detailed walkthrough of my current use case:

## Preview of both Kanban and Dataview

<img width="500" alt="Screenshot 2022-11-15 at 10 45 32 AM" src="https://user-images.githubusercontent.com/18406537/201963395-a9e806cd-8d20-44a6-9e18-8d15bd7d4f6a.png">

## Kanban
The Kanban plugin has won me over as my best media player solution. @carlonicora was right in #230 about the funky behavior of embedded players when you put them in a notes (i.e. when you scroll down the page they stop). The Kanban board somehow overcomes this behavior – the player is pretty stable and isn't disrupted any activities I tested. In my use, I am building a [Kanban DM Screen](https://youtu.be/PuZNjzwQCmI) with a list that has the embeds of mp3s I expect to play during the session so it's accessible. 

The Kanban board lets you use Metadata to populate the footer of a card. This is nice because you only need to add a link to the note that contains those values in its the metadata for it to populate the image and player. You can access this feature in the plugin's (or specific board's) settings – I included an image of the board settings I use and what the kanban's markdown looks like after:

<img width="500" alt="Screenshot 2022-11-15 at 10 47 46 AM" src="https://user-images.githubusercontent.com/18406537/201963482-0f631bcd-a90b-485c-baad-cae57d3343c6.png"> <img width="500" alt="Screenshot 2022-11-15 at 10 46 17 AM" src="https://user-images.githubusercontent.com/18406537/201963559-2b278f47-e7ef-4106-8877-4656a037007e.png">

## Dataview
Dataview use is more in the idea phase, but I anticipate a lot of value in creating views to organize the tracks in my vault. Using the image path and the synopsis would probably be valuable for most concepts I have I mind, so having them both in the frontmatter would make them accessible through dataview. Including other metadata (like genre, etc.) will enable me to make views organized by other fields.

<img width="500" alt="Screenshot 2022-11-15 at 10 46 44 AM" src="https://user-images.githubusercontent.com/18406537/201963620-ea3aad1b-234f-4d6d-9155-07ea50f803a9.png">


## JSON/CSV Converter
I'm grabbing my audio files from [Tabletop Audio](https://tabletopaudio.com). Each listing has an image, text description, and an mp3 (multiple mp3s if you have variants from the Patreon). I made a JSON that contains the info for all the tracks I've downloaded so far: [tabletop_audio.txt](https://github.com/carlonicora/obsidian-rpg-manager/files/10013622/tabletop_audio.txt)

Here is an example:
```
{
    "audio" : [
        {
            "alias": "A New Beginning", 
            "image": "a-new-beginning.jpg", 
            "tag": "audio/music-and-ambience", 
            "mp3": "277_A_New_Beginning.mp3", 
            "name": "277-a-new-beginning"
        }, 
        {
            "alias": "A New Beginning Mus Only", 
            "image": "a-new-beginning.jpg", 
            "tag": "audio/music", 
            "mp3": "277_A_New_Beginning_MUS_Only.mp3", 
            "name": "277-a-new-beginning-mus-only"
        }, 
        {
            "alias": "A New Beginning Amb Only", 
            "image": "a-new-beginning.jpg", 
            "tag": "audio/ambience", 
            "mp3": "277_A_New_Beginning_AMB_Only.mp3", 
            "name": "277-a-new-beginning-amb-only"
        }
     ]
}
```

Currently I don't include the synopsis, but I'm considering adding it in (particularly if I can use this data to populate the RPG Manager synopsis. 

Using the [JSON/CSV Importer plugin](https://github.com/farling42/obsidian-import-json), I have a [Handlebar Template](https://github.com/carlonicora/obsidian-rpg-manager/files/10014197/Handlebar.Template.-.Music.md) that will make the file and populate the metadata from the JSON. 

## RPG Manager
I considered cutting music entirely from RPG Manager, but I think it is still valuable to include relationships to Music when planning my Scenes. RPG Manager becomes the resource I reference when I add the tracks  to my DM Screen before a session.

<img width="500" alt="Screenshot 2022-11-15 at 11 03 11 AM" src="https://user-images.githubusercontent.com/18406537/201967380-da5e6598-7b96-4be5-9d60-8e715a48477d.png">

## Alternative
See the beginning. Apparently RPG Manager _does_ accept components I create without using the `Create` or `Fill` commands. This is even better than RPG Manager populating from the metadata because it means I don't have to initialize all the notes made by the CSV/JSON Importer plugin. 

Please, let me know if you think creating components this way using JSON will create any problems that I'm not aware of.

**Comment by cjolson** [comment]
Though my follow up question would be is it possible to exclude the Handlebar template from the components in the campaign? Maybe by storing it in a folder that I tell RPG Manager to ignore?  

<img width="755" alt="Screenshot 2022-11-15 at 12 05 34 PM" src="https://user-images.githubusercontent.com/18406537/201981744-f1a2a530-619f-4473-a9dc-5c3a8a0b92cd.png">

**Comment by sigrunixia** [comment]
Quick note-

In searching on another issue and coming across this this [message thread](https://discord.com/channels/686053708261228577/840286264964022302/1040664282603462716), and now seeing that the the developers have already begun working on implementing [something](https://trello.com/b/Psqfqp7I/obsidian-roadmap), I think we will see greater add-on interoperability sooner than later.

**Comment by sigrunixia** [comment]
As an update, in the 1.10 insiders that was released today, this API was added. So expect this functionality to for adding to much more cleanly and easily read and write from frontmatter sooner than later. 
https://github.com/obsidianmd/obsidian-api/blob/master/CHANGELOG.md

How this will work for RPGM, we'll need to poke into. However, it will absolutely make reading from YAML more reliable, and writing to it the same.

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
