### ISSUE TITLE
[Minor Bug] Marking Complete on Module removes YAML from RpgManagerData

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#243]
## Scope

When you mark a module as complete within RPGM, the YAML within the code block for "complete" disappears completely versus switching to true. 

### To Reproduce

1. Look at RpgManagerData on an uncompleted character, scene, clue, etc. 
2. Observe `complete: false`
3. Close the RpgManagerData code block
4. Mark the module as complete
5. Check the RpgManagerData code block again
6. Observe there is no sign of `complete`.

### Expected behaviour

The expected behavior is `complete` would remain and would become `complete: true`. 

### Screenshots
![image-pre](https://user-images.githubusercontent.com/68425372/201799168-88246f47-c115-4cfb-ba18-58dd21c8f5a6.png)

![image-post](https://user-images.githubusercontent.com/68425372/201799174-3f38ac41-803e-46b6-97f7-d74619eb0855.png)

### Desktop (please complete the following information)
RPGM 3.2.3.

**Comment by carlonicora** [comment]
Hi @sigrunixia 

Thanks for the report. This was a design decision that was taken to keep the data as light as possible. Setting `completed` to `true` instead of removing it completely is easy, but before I dig into it, can you give me the rationale to keep the metadata present? I have always thought: _once done, it's done..._

**Comment by sigrunixia** [comment]
Ah, I had thought it was a bug because I had no indication it was intentionally removed. :) I would need to update documentation in that case. 

It does not matter to me what you decide in this, since I think the complete versus non-complete usage base is small (I wish we had analytics on this). That being said, some quick top of mind rationale.

- If a user accidentally hits complete (which is arguably easier to do now with the way the formatting is redone for the modules), then they would not only have to type out the word complete: false, but they would also have to get the indentation right in the code block. Easy enough to explain in documentation, but another step where things can get messed up on their end.
- If there was a way to determine that the need for a Complete versus Not-Complete was greater than 1, then the way I would handle it is within the RPG-Manager right bar (after you click the button on the left side bar), list the completed elements under a new heading > `Completed Elements` and then when those are clicked, do a pop-up that states "Do you wish to mark this element as incomplete?"

Otherwise, makes no difference to me. I'll make a note to redo my documentation on how to mark a module as incomplete if thats what you want to do.

**Comment by carlonicora** [comment]
`complete` flag set to `true` instead of removing it from the code block.

Waiting for `v3.2.5` release
