### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lazarusomega2000** [carlonicora/obsidian-rpg-manager#245]
## Scope

When I type in the scene description into RPGM's new input block, links to characters/items/stuff do not autolink properly and when I go into the datablock and edit them appropriately to get Obsidian to link up the people it freezes up for seconds at a time. Each time I try to fix it, the system just locks up.

### To Reproduce

Steps to reproduce the behaviour:

1. Make a new scene
2. Enter the description and include a wikilink '[[?]]' to any given content.
3. Check to see if it links up to display the content (it doesn't in mine)
4. Go into the code block at the top of the screen and edit the link (will show a drop down most times to select appropriate item/character/location)

My system usually locks up somewhere in the drop down step

### Screenshots

![image](https://user-images.githubusercontent.com/32077293/202502463-b2a1ceb8-30e6-4b52-b8bd-b4dcc9cfc346.png)

**Comment by carlonicora** [comment]
@lazarusomega2000 Let me look into it and I will release a patch asap!

**Comment by carlonicora** [comment]
Hi @lazarusomega2000 

I will need a couple of explanations

> Make a new scene
OK

> Enter the description and include a wikilink '[[?]]' to any given content.
Where do you enter the description? Is it the editor and in the synopsis?

>Check to see if it links up to display the content (it doesn't in mine)
Are you meaning the relationships? Which relationships are you adding, is the element you are linking a valid RPG Manager `element`?

> Go into the code block at the top of the screen and edit the link (will show a drop down most times to select appropriate item/character/location)
Why are you editing the link? It is not working? It is saved incorrectly?

Could you share a video screenshot of the issue?

Thanks

**Comment by handcraftedsource** [comment]
Hi @carlonicora

I've recently started having this problem as well. Attached is a small video about it. I have started with a completely fresh Vault.

![freeze-bug](https://user-images.githubusercontent.com/28440782/202893138-af39e769-9453-4867-935d-80093505f54c.gif)

Hope it helps to find the error.

**Comment by carlonicora** [comment]
@handcraftedsource @lazarusomega2000 Thanks for it. I am looking into it and trying to fix the issue

**Comment by carlonicora** [comment]
@handcraftedsource @lazarusomega2000 I have finally found the bug. Luckily enough, it had nothing to do with the database, but it was a component in the right view (_which I never use_) that was calling a function recursively, clogging the system.

It should be solved in [3.2.7](https://github.com/carlonicora/obsidian-rpg-manager/releases/tag/3.2.7) that has been released a few minutes ago.

Please reopen the task if your issue is not resolved!
