### ISSUE TITLE
[BUG] Error loading with synchronised vault

### ISSUE THREAD

**Issue by SwitchMcBlade** [carlonicora/obsidian-rpg-manager#246]
## Scope

RPG manager fails to load when using a vault synchronised from another device.  It states it requires to update data from 1.2 to 3.2.4 then hangs and fails to complete.  Opening the Inspector shows an error that looks like a code error with the updater script rather than something I think I can fix.

### To Reproduce

1. Create vault on device A with obsidian and enable rpg manager.  In my case on Steamdeck.
2. Synchronise vault to device B using Nextcloud,  In my case an Ubuntu 22.04 laptop and windows 8 tablet.
3. Install obsidian and link it to the synchronised vault.  It asks if you want to trust the vault and want to enable the plugins, click ok.
4. RPG Manager will disable a message stating it needs to update the database, when you click to start it fails to complete showing it has processed twice as many files as exist.
5. The vault continues to open correctly on the original device (steamdeck)

### Expected behaviour

The vault should just load as the versions of RPG manager on both devices match.

### Screenshots
![Screenshot from 2022-11-18 08-10-34](https://user-images.githubusercontent.com/70704389/202661574-34bebbf0-e292-4651-9eea-4d52ea81eeca.png)

### Desktop (please complete the following information)

 - OS: Ubuntu 22.04
 - Obsidian 1.0.3
 - Version 3.2.4

Other system
- OS: Windows 8
- Obsidian 1.0.3
- Version 3.2.4

On the working source system
- OS: SteamOS 3.4
- Obsidian 1.0.3
- Version 3.2.4

**Comment by carlonicora** [comment]
Hi @SwitchMcBlade 

Let me have a look into this and I will release a patch asap.

**Comment by carlonicora** [comment]
Fixed a small component that was showing an error.
The updater should be fine right now... Leaving open for testing when `v3.2.5` is released

**Comment by SwitchMcBlade** [comment]
That has resolved it, thank you very much for the fast response.

**Comment by carlonicora** [comment]
@SwitchMcBlade thanks for confirming!
