### ISSUE TITLE
[Minor Bugs] 3.3 Beta Testing Minor Issues Thread 

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#248]
## Scope

This thread is for very minor issues. Typos, minor graphical glitches, and other small things that can be fixed in one go.

Major issues, such as large "This is absolutely not working" should continue to be reported in their own threads as in-depth back and forth conversation may need to happen. 

### How to Report

1. Each comment contains one issue.
2. Include in your comment the issue in a checkbox format. See first comment for example.
3. Include screenshots if able

**Comment by sigrunixia** [comment]
- [ ] Adventure Plot Creation Wizard Question 6 makes no grammatical sense

## Current Question

"What does convince the player characters to achieve their perceived goal?"

## Screenshot

![nosense](https://user-images.githubusercontent.com/68425372/202920239-fe0d3bbd-afff-41e3-9819-e021038394a7.png)

## Suggested Alternative

"What convinces player characters to achieve their perceived goal?"

**Comment by sigrunixia** [comment]
- [ ] Adventure Plot Creation Wizard Question 9 Has a Typo for 'Triump'

## Current Question

"How are they going to **triump** and reach the true goal of the adventure?"

## Screenshot

![Typo1](https://user-images.githubusercontent.com/68425372/202920906-9fe84cec-731f-48fc-a5dd-b94ab63b8067.png)

## Suggested Fix

"How are they going to **triumph** and reach the true goal of the adventure?"

**Comment by carlonicora** [comment]
@sigrunixia both corrected in 3.3.0-2
