### ISSUE TITLE
[FEATURE] 3.3 Plot Wizard - Adventure

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#250]
## Scope

Attempt to clean up and clarify the Plot Wizard - Adventure Introduction Page. There is some typos, inconsistencies, and condensation that can be done. 

Anything bolded is also titlecased by default. 

## Screenshot

![Plot-creation-Wizard](https://user-images.githubusercontent.com/68425372/202922241-71a4d03a-4172-416c-ae46-c91caeae669e.png)

## Question
Do we want to continue to use the word interesting, or switch it with a more neutral and less subjective word such as "varied"?

### Paragraph One

"The **Plot Creation Wizard** is a tool that helps you create a more consistent plot without worrying about knowing anything about ABT or Storycircle mechanics. Follow the prompts in the next few pages and the plot will be organized for you."

### Paragraph Two
"The plot is structured to provide an **interesting** storyline for your player characters, identifying two main goals for the **Adventure**. 

### Paragraph Three

"The first goal is what the player characters believe they want or need as the goal. The second goal is [_Not sure how to best word this, ideas?_]. This storytelling structure creates minor narrative tension in the game, and through narrative tension you achieve variety. Take into consideration Luke Skywalker. When he left Tatooine with Obi-Wan Kenobi, he was under the impression that he was going to rescue Princess Leia and then continue to work on becoming a Jedi. However, once she was rescued from the station, he became aware that she would not be truly rescued until the station itself was destroyed. The logic is the same, and in storytelling, it works!"

### Paragraph Four

"Two areas in the plot creation wizard offer the ability to also create a **Clue** alongside those plot elements, which allow you to expand upon who your what your player characters will also interact with in that plot point. The suggestion is to make these types of clues as relevant and interesting as possible, and identify three other elements (_mainly Non-Player Characters and Locations_) where player characters can learn about the clue. These types of clues are meant to mark a moment of passage for the player characters in the storyline, and should be unavoidable to find."

## Continuing Thoughts

Parapgraphs 3 and 4 feel rougher, and may need another pass by yourself and I. It feels like almost too much we're trying to fit on one page, and it may be better up to have a summary on this page, and then add a tiny bit of explanation per each question page.

**Comment by sigrunixia** [comment]
Also, looks like Act is the same. Does Act have the same "goals" as Adventure?

**Comment by carlonicora** [comment]
@sigrunixia I have updated the text, and indeed the Adventure and the Act behave in exactly the same way.
