### ISSUE TITLE
[BUG] Can't edit relationship

### ISSUE THREAD

**Issue by Zorgonaute84** [carlonicora/obsidian-rpg-manager#253]
Hello,

Everything works fine at the begining, but now, I can't edit some relationship.

Is it possible that the issue come from the fact that I reordre my note into folders and subfolders ? (All links works well)

Any idea how to fix that ?

Thanks in advance :-)

**Comment by carlonicora** [comment]
@Zorgonaute84 did you move the files in the finder/file system or from inside Obsidian (the first will not work, the second will update all the relationships).

You can check the `RpgManagerData` code block and check that the relationships point to the right file.

Also, please feel free to send me screenshots of the `RpgManagerData` codeblock and the Relationship modal, so I can check it.

**Comment by Zorgonaute84** [comment]
I edited inside Obsidian. 
I noticed that the bug appear at the same time that the autocompletion stop working inside RPGManager pop up.

i'll have a look on the RpgManagerData :-)

**Comment by Zorgonaute84** [comment]
Humm very interesting... The relationship look edited well, but not display on the note...

![image](https://user-images.githubusercontent.com/13313177/203060714-8384c3b2-4540-4bb8-8b2a-095b9839b99e.png)
![image](https://user-images.githubusercontent.com/13313177/203060786-62074cf0-cb27-4e7e-ad87-f323fbb676d7.png)

**Comment by carlonicora** [comment]
@Zorgonaute84 have you tried restarting Obsidian?
Also, check the inspector window to see if there are strange errors popping up (and screenshot them for good measure) :D

**Comment by Zorgonaute84** [comment]
Restart Obsidian doesn't change... :-(
What do you mean by "Inspection Window" ?

**Comment by carlonicora** [comment]
You can see a window showing you the console log. In a Mac you open it pressing Option+Command+I.

![Screenshot 2022-11-21 at 14 01 00](https://user-images.githubusercontent.com/63145/203061659-258a7603-1928-448c-a685-3289f65736f3.jpg)

**Comment by carlonicora** [comment]
BTW: I can see something not working 100% on my side as well, so I will check it

**Comment by Zorgonaute84** [comment]
Ahah well, happy to report you something interesting :-)

**Comment by Zorgonaute84** [comment]
Dont' know if it's help, but this is the screenshot of a note with the issue : 
![image](https://user-images.githubusercontent.com/13313177/203062263-373d58d0-846c-4cd6-ae6a-acb5a6adb796.png)

**Comment by Zorgonaute84** [comment]
If it could help, editing relationship with :  

NonPlayersCaracters is working
Location is working
Events is NOT working
Clue is NOT working

**Comment by carlonicora** [comment]
I am checking, but after reading something wrong I am getting somewhere now.

Can you please let me know the following:
- in which type of element you are having this issue
- how can you reproduce the issue step by step
- which type of element are you linking to a specific type of element (example: events with events, clues with clues, clues with events...)

The most important part is letting me know the step by step (either you write it or you add a video screenshot) and I will be able to better support you

**Comment by Zorgonaute84** [comment]
For example, I'm trying to edit the relationship between NPC and Event : 

This is the event. You can see in the description the link to the NPC : 
![image](https://user-images.githubusercontent.com/13313177/203065738-d1e4320c-c106-4192-af0e-baef426ff349.png)

Into the NPC, the event is reported as bellow : 
![image](https://user-images.githubusercontent.com/13313177/203065859-8e3b15a2-cda2-46a9-a5fc-0c990e38fea3.png)

But when I click on the edit icon, and fill the pop up window, the relation ship is not edited. (But the RPGManager Data block is updated).

**Comment by carlonicora** [comment]
Ok, I was able to reproduce the issue. Let me look into it

**Comment by Zorgonaute84** [comment]
I don't have relationship editing issue, if the link between NPC and event is created into the NPC.

In the note (note in RPGManger block), I created a link to an event, and in the block edit succesfully the relationship to it.

(this test was on an other NPC and other event) (No link from the event to the NPC).

**Comment by Zorgonaute84** [comment]
I don't know, but I can backup my vault, and try it. No problem

I guess, it's just like a copy/paste into the vault plugin folder ?

**Comment by carlonicora** [comment]
Do this:

1. Create a backup of your vault
2. Replace the files in the rpg-manager folder with the ones in the zip
3. open and test

Please do let me know if the bug is fixed and if you have any other issues.

[rpg-manager-3.3.0-4.zip](https://github.com/carlonicora/obsidian-rpg-manager/files/10057527/rpg-manager-3.3.0-4.zip)

**Comment by Zorgonaute84** [comment]
Hey, it's all good !
No other issue for the moment, but I just test.
But I also have the issue that auto completion (to create links) didn't work into the pop up forms.
I'm pretty sure that it's work this morning.

**Comment by carlonicora** [comment]
@Zorgonaute84 it is really strange...
One thing to keep into consideration is that the auto-completion in the modals refers to other RPG Manager `element` and NOT to every note in Obsidian.
Are you trying to link notes that are not RPG Manager elements?

**Comment by carlonicora** [comment]
Yes please! :)

Also, try and add as many details as you can (examples of where the issue happens, how you are trying to do things). Video screenshots are also appreciated, as they make my life much easier! :D
