### ISSUE TITLE
[BUG] Autocompletion didn't work in RPGManager pop-up

### ISSUE THREAD

**Issue by Zorgonaute84** [carlonicora/obsidian-rpg-manager#254]
Hello,

I'm having trouble with the auto-completion to create links in the RPGManager forms.

Everything was working correctly at the beginning when I first tried it.

1/ I created my campaign, my adventure, NPCs, places, events at the root of my chest (default option).

at this moment everythings worked

2/ I reorganised my RPG vault like that :
![image](https://user-images.githubusercontent.com/13313177/203103611-2454d7cc-cd82-4441-8d56-5b929491c705.png)

3/ Then, fey moments later, I noticed that auto completion doesn't work... (not sure that the reorganisation is the root cause)
![image](https://user-images.githubusercontent.com/13313177/203103831-c5f73f1f-f79c-4b99-a17e-5ede715ab490.png)

Thanks :-)

**Comment by Zorgonaute84** [comment]
Hi,

No problem to share my vault throw discord screen sharing, it's a new vault mostly empty (except of this campaign).
Don't know where are you based, but if it's ok for your regarding the clock time, in 3hours ?

**Comment by carlonicora** [comment]
@Zorgonaute84 Either that or just pack zip vault and send it over. My id is carlo#6040

I am CET, not sure where I will be 3 hours from now! :D

**Comment by carlonicora** [comment]
@sigrunixia could you please check this? Thanks

**Comment by sigrunixia** [comment]
Sure! I'll be around in the RPG-Manager-Support thread, and can see what I can do.

**Comment by sigrunixia** [comment]
I also just found some bugs related to this, so it is not something you are specifically doing, @Zorgonaute84. This will require a patch by Carlo which will have to happen tomorrow as he has retired for the evening.

A temporary fix that may help you bypass this and get things working in the short term for the evening is do the following:
1. Restart Obsidian
2. In the Obsidian settings, if Enable Wikilinks is not enabled, enable it. If it is enabled, toggle it off then on. Go to a RPGM Page and try to create a link as before. It should be able to. 
3. Once the link is made, if you started with wikilinks off, you can turn the setting off and RPGM should maintain it until vault is restarted or you switch to another campaign.. Or move it 😃 .

@carlonicora Here is the error I managed to log a lot of. I had no issue getting autocompletion working in one campaign at all, even in my relevant markdown link vault. However, as soon as I switched to another campaign within the same vault... inferno opened up and no matter what I do I cannot get any links to generate. 

Furthermore, if it's not this error, it is the console complaining about table forms. 

[obsidian.md-1669075167173.log](https://github.com/carlonicora/obsidian-rpg-manager/files/10061442/obsidian.md-1669075167173.log)

**Comment by carlonicora** [comment]
@sigrunixia @Zorgonaute84 No matter what I have tried, I am not able to reproduce the issues you are having :(

Would it be possible to record a video or to have a quick screen sharing for me to understand what is going on? 

Thanks

**Comment by sigrunixia** [comment]
I think I have a fix. I corrected this within my vault. Please try this out in yours, @Zorgonaute84, and confirm.

1. In your campaign folder and files, check the alias entry for every markdown file. It must be in one of the following formats.

Note: alias and aliases can be used interchangeably here. 

`alias: [one, two, "three with spaces", "fours' pours special characters"]`

or 

```
---
alias: 
  - one
  - two
  - "three with spaces"
  - "fours' pours special characters"
---
```

3. Be on the lookout for weird alias entries that look like this: 
`alias: ["Q","u","i","n","n"," ","H","i","g","h","t","o","p","p","l","e"]`

I'm still trying to determine what circumstances cause that to fill from character/npc, where it takes an H1 and Turn it into an alias. 

4. What may have worked prior in Obsidian as `alias: [Isolde's]` may not work and will now need to be alias: ["Isolde's"]. 

In my case, it was one file that had aliases: [Joseph's] as what broke things.

**Comment by Zorgonaute84** [comment]
You right !!!

I checked all my YAML, don't know why, but I have some different format for tags and alias too. (Maybe from the Run meta plugin)
The one who fixed the issue was a simple string alias.

alias : "My alias sentences" -> Broke the auto completion
alias:  ["My alias sentences"] -> Reactivate it

**Comment by sigrunixia** [comment]
Awesome! Glad it's working for you! 

Different addons have different allowances for how it handles YAML, but it does look like [Obsidian devs](https://trello.com/b/Psqfqp7I/obsidian-roadmap) have prioritized working on a stable YAML/metadata editing API to [fix things like this](https://discord.com/channels/686053708261228577/840286264964022302/1040664282603462716) in the future. It _should_ also address alias handling.
