### ISSUE TITLE
[BUG] Timeline when using Calendar of Harptos is not in order

### ISSUE THREAD

**Issue by cjolson** [carlonicora/obsidian-rpg-manager#255]
**_WARNING:_** This post contains _Waterdeep: Dragon Heist_ spoilers

## Scope

I'm using the Calendar of Harptos for Fantasy Calendar. It appears that my timeline is not in order of date. I'm not sure what the order is, though it does appear to be organized by type.

### To Reproduce

1. Make some events. 
2. Set Fantasy Calendar to your calendar in RPG Manager. 
3. Set the dates of the events. 
4. Look at the timeline.

### Expected behaviour

In the screenshots below, I would expect the first event to be: "Destruction of Neverwinter".

### Screenshots

<img width="600" alt="Screenshot 2022-11-22 at 8 34 38 AM" src="https://user-images.githubusercontent.com/18406537/203327597-88e4cf57-74ef-4b26-a4e0-8bda7086bb1d.png">
<img width="600" alt="Screenshot 2022-11-22 at 8 34 43 AM" src="https://user-images.githubusercontent.com/18406537/203327603-f20b45f3-b8aa-45ce-8a53-c931bf3c70d0.png">
<img width="600" alt="Screenshot 2022-11-22 at 8 34 46 AM" src="https://user-images.githubusercontent.com/18406537/203327608-849cfd85-db06-4921-b939-e177602a04a2.png">
<img width="600" alt="Screenshot 2022-11-22 at 8 34 54 AM" src="https://user-images.githubusercontent.com/18406537/203327611-11e49edb-82a0-4a50-af01-f0421c2386f9.png">
<img width="600" alt="Screenshot 2022-11-22 at 8 34 59 AM" src="https://user-images.githubusercontent.com/18406537/203327616-e4634239-233c-4494-bcc2-2a1b234e8a73.png">
<img width="600" alt="Screenshot 2022-11-22 at 8 35 04 AM" src="https://user-images.githubusercontent.com/18406537/203327618-d7470d15-e581-4348-9744-ac35ee9e15a3.png">

### Desktop (please complete the following information)

 - OS: Ventura 13.0.1
 - Obsidian: v1.0.3
 - RPG Manager: v3.3.0
 - Fantasy Calendar: v2.3.10

**Comment by cjolson** [comment]
Just realized, they are ordered by type and then alphabetically by name.

**Comment by sigrunixia** [comment]
Testing with Golarion Pathfinder Calendar (Because it is a beast of a calendar), and I get something a bit different. The event/date order does not quite make sense. I think it is trying to assign a time.

Here is a Screenshot and some Logs for you @carlonicora  
![Testy](https://user-images.githubusercontent.com/68425372/203674085-33dd79cd-8bb5-41b8-83e7-2552c319d531.png)
[obsidian.md-1669253249027.log](https://github.com/carlonicora/obsidian-rpg-manager/files/10080162/obsidian.md-1669253249027.log)

**Comment by sigrunixia** [comment]
Can confirm this appears fixed in 3.4.05.
