### ISSUE TITLE
[BUG] Timeline event order issue

### ISSUE THREAD

**Issue by Zorgonaute84** [carlonicora/obsidian-rpg-manager#256]
Hello,

It looks to have an issue about the event order in the timeline : 
![image](https://user-images.githubusercontent.com/13313177/203657229-abdc8d6b-543e-4a28-9a3e-0b4b86ee191f.png)

**Comment by sigrunixia** [comment]
Not merging this one and CJ's as it may be a separate one due to CJ using FC.

**Comment by carlonicora** [comment]
@Zorgonaute84 I think there has been a misunderstanding. This is not the `timeline` but the order of the events in the campaign (I guess). Can you confirm it?

**Comment by Zorgonaute84** [comment]
> @Zorgonaute84 I think there has been a misunderstanding. This is not the `timeline` but the order of the events in the campaign (I guess). Can you confirm it?

Exact, sorry for the misunderstanding. The Timeline is good, but the event order in the campagne note is not. (Looks ordered by creation date).

I prefere to use the event order instead of timeline, because I feel that the timeline is less readable. (Looks to have font size issue)

![image](https://user-images.githubusercontent.com/13313177/204101333-d5857848-ccef-4664-a729-03ea991192eb.png)

**Comment by carlonicora** [comment]
@Zorgonaute84 Thanks for the clarification. I have fixed the ordering in the list of events, and I will look into the strange behaviour of the timeline. I bet it is a CSS issue

**Comment by sigrunixia** [comment]
As far as events on a campaign page, appears fixed in 3.4.05.
