### ISSUE TITLE
PC: Duplicate Question

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#26]
On creating a new player character and following the generated questionnaire, this is the 6th question:
"Do you have any allergies, diseases or other physical or mental weaknesses?"

Later on in the questionnaire, this last question is asked. 
"Do you have any allergy?"

Based on its positioning, it feels like it was meant to be "Do you have an enemy" or similar.

**Comment by carlonicora** [comment]
@sigrunixia the allergy question is duplicated (my bad). But I like the idea of adding the "_enemy_".

Will release it in v1.0.2 later today

**Comment by carlonicora** [comment]
released in v1.0.3
