### ISSUE TITLE
Moving elements

### ISSUE THREAD

**Issue by carlonicora** [carlonicora/obsidian-rpg-manager#261]
### Discussed in https://github.com/carlonicora/obsidian-rpg-manager/discussions/257

<div type='discussions-op-text'>

<sup>Originally posted by **carlonicora** November 24, 2022</sup>
Hello everyone,

Working on `v3.4` I have been considering a change in the structure of the elements, in particular how to move the elements from one parent to another, for example moving one act from one adventure to another.

Currently, RPG Manager provides a "_Move_" functionality in the bar underneath the element title that opens a modal where you can redirect the element to another parent.

My proposed option is to add in each element the parent element, with the possibility of selecting a different parent. The functionality would be similar to how you select the current adventure, act and session in a campaign or the session in a scene.

My question is: **what's the most reasonable approach: the current version, or a simplified dropdown in the element?**

From one side I feel that having a "move" button is not clear, but from the other side I am asking myself how often this functionality is going to be used. Changing the functionality would make it much easier to move things around, but this may be an overkill for a rarely-used functionality.

Any thoughts appreciated

Carlo</div>

**Comment by sigrunixia** [comment]
Confirms this works in 3.4.05
