### ISSUE TITLE
[BUG] Unidirectional Relationships imposing Bidirectional Relationships

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#262]
## Scope

Relationship Issue

New Unidirectional Relationships are creating Bidirectional Relationships in the connected relationship Elements. 

### To Reproduce

Steps to reproduce the behaviour:
1. Create a new unidirectional relationship.
2. Select the note you created the relationship to.
3. Check the linked Elements/Relationships and observe how it appears to be a bidirectional relationship. 

### Expected behaviour

When selecting a unidirectional relationship in the relationship manager, it is expected that the relationship remain a one-way relationship.

### Video

Video Link here: https://youtu.be/qPyShGMSST0

### Desktop (please complete the following information)
Obsidian 1.0.3
RPGM 3.3

**Comment by carlonicora** [comment]
Hi @sigrunixia 

I tried to reproduce the bug, but can't. Also, the video is marked as private, so I can't see it :(
