### ISSUE TITLE
Add Internationalisation

### ISSUE THREAD

**Issue by carlonicora** [carlonicora/obsidian-rpg-manager#265]
Ref: [i18next](https://www.i18next.com/)
### Discussed in https://github.com/carlonicora/obsidian-rpg-manager/discussions/264

<div type='discussions-op-text'>

<sup>Originally posted by **Zorgonaute84** November 26, 2022</sup>
Hello,

Thanks again for your amazing work.

I'm not a big fan of the titles provided in the defaut RPGManager templates, So for my first campaing, I overwriting them each time. For the second ones, I want to use custom templates. I tried to create a simple template with only 2 customs titles, selected it when creating a new campaign, but it looks not working. I guess that I missed something.

So there is somewhere a documentation about how to create templates in the good way ?

PS : There is a possibility to translation some informations into the RPGManager blocks ? Like Clue -> Indice (French) etc... If this have to be done into the code, I can help you :-)</div>

**Comment by carlonicora** [comment]
@Zorgonaute84 I am implementing the internationalisation, and soon I will ask for your support for the French translation (_I will do the English and Italian_).

How much are you comfortable with Git and creating pull requests? If you are I can tell you which files you can edit and do a pull request, otherwise I can pack the files and send them over.

PS: all this will be ready to process when I finish the internationalisation

Ciao
Carlo

**Comment by Zorgonaute84** [comment]
Hello, Sorry for the late, I was very busa last days.

I never used Git for developing, but I'm confident to used it. No problem.

Tell me what files and I'll

**Comment by carlonicora** [comment]
@Zorgonaute84 no problem at all!!!

When we complete the internationalisation I will keep you posted!

`Merci Beaucoup`!
