### ISSUE TITLE
[BUG] Custom templates are not working any longer

### ISSUE THREAD

**Issue by carlonicora** [carlonicora/obsidian-rpg-manager#266]
## Scope

Using a custom template when creating an `element` does not add the information contained in the template to the newly created `element`

### To Reproduce

Steps to reproduce the behaviour:
1. Start creating a new `element`
2. Select a custom template
3. See that the content of the custom template are not in the new `element`

### Expected behaviour

See the information contained in the custom template

**Comment by sigrunixia** [comment]
Can confirm custom templates work again in 3.4.05. 

Note: I did not test the extent of testing beyond making sure it generates, and that it places everything within the modals (i.e, makes the UUID the very last thing in the note). I'll be doing in-depth testing when I work on #267 at same time.
