### ISSUE TITLE
[BUG] Unwanted text deletion when updated to 3.4

### ISSUE THREAD

**Issue by StarSword-C** [carlonicora/obsidian-rpg-manager#270]
## Scope

I had statblocks for a couple of armors on a subplot component. Somehow, in my old version of the file, they ended up below the hidden RpgManagerID footer, and when I updated to 3.4 the program started deleting them from the file. Thankfully I managed to recover the text by hitting Undo and copying everything before it was deleted again. Moving the information above the footer resolved the issue.

I have since confirmed that anything you type below the footer will be deleted right away. I'm assuming this is a result of the functionality to add relationship links to the graph view, but it gave me a few moments of panic because those statblocks took forever to make.

### To Reproduce

Steps to reproduce the behaviour:
1. Type something below the footer (the ` ```RpgManagerID ` codeblock).
2. Wait a couple seconds. The text will delete itself.

### Expected behaviour

I don't know how possible this would be, but maybe there's some way to automatically move extraneous text from below the footer to above it?

[Tragedy of Yamashita Mizuki OLD.md](https://github.com/carlonicora/obsidian-rpg-manager/files/10143593/Tragedy.of.Yamashita.Mizuki.OLD.md)

**Comment by carlonicora** [comment]
@StarSword-C Yes, I think the update removes everything underneath the RpgManagerID codeblock :(

Will double check and fix soon

**Comment by carlonicora** [comment]
@StarSword-C the bug has been fixed in `3.4.2`

**Comment by StarSword-C** [comment]
Much obliged
