### ISSUE TITLE
[FEATURE] Ability to personalize default RPG Manager Header/Lists codeblocks (with templates?)

### ISSUE THREAD

**Issue by cjolson** [carlonicora/obsidian-rpg-manager#272]
## Scope

I'm noticing areas where I'd like to customize the RPGManager codeblock more often. As an example, I would prefer to include Scenes in the footer codeblock instead of the header for Sessions. It makes more sense for my organization and how I access information during my game. However, this seems like something that falls into the category of personal preference and what makes sense to me might not make sense to someone else. Currently I can adjust the codeblocks manually for the setup that fit my preferences, but this is tedious to do every time I make a new component.

> What is and isn't included in the header and footer codeblocks for various components could be personalizable. The ability to define my own default organization of info would be a major improvement in my use of RPG Manager.

### Describe the solution you'd like

Currently, custom templates for RPG Manager do not require me to provide RPG Manager codeblocks. Creating the component populates the codeblocks automatically (sandwiching the content in the template). I wonder if it is possible for me to include the codeblock configuration that fits my preferences in the template instead – and for RPG Manager to use what I provide instead of the default – so I don't have to adjust the codeblocks each time I make a new component?

### Alternatives

The main alternative I can think of would be adding controls in Settings. 

### Additional context
- I provided an example above (wanting scenes in the footer for sessions), but this is not the only use case I've run into where I wish for more flexibility in defining the configuration of the codeblocks. I think there are a few components where I want to shift things around, include/exclude certain lists, switch up the list ordering, or maybe even omit the header entirely. This is why I'm more interested in a personalization option – as opposed to recommending the changes I want to see.
- The main point that got me thinking about this was when the header contains a list that is very long. If the most important info I want to reference is often in the note content and/or the footer, I have to scroll a lot to find it which can feel disruptive mid-session.

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
