### ISSUE TITLE
[FEATURE] More tooltips in Scene Builder

### ISSUE THREAD

**Issue by Pachtjuilaard** [carlonicora/obsidian-rpg-manager#273]
## Scope

I tend to forget what the different stages in the story circle mean, or what 'exciting' means. A few more tooltips explaining these terms would help a lot. Encounter types are already being explained in the scene builder, something like that would already help a lot. 

### Describe the solution you'd like

Tooltips and descriptions for the different stages in scene builder, and for the 'Exciting?' toggle. 

### Alternatives

-

**Comment by lucastucious** [comment]
I second this.

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
