### ISSUE TITLE
[BUG] Adding images by URL turns all characters to lowercase, breaking some URL's.

### ISSUE THREAD

**Issue by Pachtjuilaard** [carlonicora/obsidian-rpg-manager#274]
## Scope

When using the Gallery modal to add images, the image sometimes becomes unavailable when trying to add a caption. In the RpgManagerData code block, the URL changed to all lowercase. Manually pasting the URL in the code block fixes it.

### To Reproduce

Steps to reproduce the behaviour:
1. Gallery --> Add Online Image
2. Paste Image URL
3. Click Add Image, then click again to add caption
4. See thumbnail being unavailable.
5. Check code block, see that the URL there differs from the URL you've just pasted in.

**Comment by carlonicora** [comment]
@Pachtjuilaard Hello and thanks for the report. I have found and squashed the bug. It will be released with `v3.5`

**Comment by carlonicora** [comment]
@Pachtjuilaard this should be fixed in `3.4.5`
