### ISSUE TITLE
[BUG] Data structure update stuck

### ISSUE THREAD

**Issue by Zorgonaute84** [carlonicora/obsidian-rpg-manager#275]
Hello,

I just updated the plugin to 3.4.4. I had the warning to update the data structure from 3.1 to 3.4 (I already was on 3.3.0.4), but  it stuck to this screen  
![image](https://user-images.githubusercontent.com/13313177/209473150-a9c15d71-5a09-4aad-85dd-e0578b1f5ed5.png)

Now, all notes looks broken. Any idea ?

**Comment by carlonicora** [comment]
Hi @Zorgonaute84 

There are two things I can see here. The first is the versioning, the second it the real issue.

The updater checks when is the last version in which data has been changed. In this case the changes required by RPG Manager were in 3.1 and then in 3.4, it means that the **version of the data** (not of the plugin) is updated. Everything is correct, then.

The fact that you can't update is worrying. Quick questions:
1. Have you backed up before upgrading?
2. Have you checked the Inspector to see any errors?

If you send the error I may be able to support you!

Ciao

**Comment by carlonicora** [comment]
@Zorgonaute84 I have updated RPG Manager to 3.4.5
Can you please check if you still have the same issue?

**Comment by sigrunixia** [comment]
@Zorgonaute84 Are you still having issues with the latest update?

**Comment by sigrunixia** [comment]
No problem. :) Thank you for responding. I'll go ahead and close this issue.
