### ISSUE TITLE
[BUG] Android

### ISSUE THREAD

**Issue by Venyom** [carlonicora/obsidian-rpg-manager#276]
## Scope

The plugin dont work on android. I can't create a new campaign.

### To Reproduce

Steps to reproduce the behaviour:

1. Go to 'create new campaign'
2. Click on 'create'

### Expected behaviour

Create a new campaign

### Smartphone (please complete the following information)

 - Device: [e.g. Redmi 10 Pro]
 - OS: [Android newest Version]

### Additional context

Please help me so i can use this great plugin.

**Comment by carlonicora** [comment]
@Venyom can you please give me a few more information on this?

In particular, what happens when you click the "Create" button on the new campaign?

**Comment by carlonicora** [comment]
@Venyom I have pushed `3.4.5` which should solve this issue
