### ISSUE TITLE
[FEATURE] I would like to be able to add relationship references from outside of a given campaign. 

### ISSUE THREAD

**Issue by catrone3** [carlonicora/obsidian-rpg-manager#281]
## Scope

Is your feature request related to a problem? Please describe.

I try to keep all of my campaigns in the same instance of the Shadowrun world, I have found that my players like this as when timelines overlap they can have their current characters learn about the outcomes of other campaign events.

### Describe the solution you'd like

I would like to be able to have an outside group of Characters(both player and non-player), Locations, and Factions that is not under any direct campaign but can be reference from any campaign. Even if this is just with using tags that the campaigns can search through.

### Alternatives

The ability to share Characters(both player and non-player), Locations, and Factions across campaigns. preferably without duplicating the files

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
