### ISSUE TITLE
Error on adding a Faction component

### ISSUE THREAD

**Issue by StarSword-C** [carlonicora/obsidian-rpg-manager#282]
Trying to add a Faction component to the vault for our _War for the Crown_ run and hit an error message immediately upon creation of the note.
![image](https://user-images.githubusercontent.com/58320836/213885314-6bb6d2db-c92b-4305-ade2-ebfab9f47ceb.png)

Have attached the two files referenced.
[Fiorina's agents.md](https://github.com/carlonicora/obsidian-rpg-manager/files/10472948/Fiorina.s.agents.md)
[Fiorina Mazzanti.md](https://github.com/carlonicora/obsidian-rpg-manager/files/10472949/Fiorina.Mazzanti.md)

**Comment by StarSword-C** [comment]
Rebooting the program appears to have fixed the issue.

**Comment by sigrunixia** [comment]
Before closing this, I'll add that much like dataview can have a cache and refresh component, so can RPG-Manager. This is a limitation of running these programs within Obsidian, sadly.

What can help is updating your Obsidian installer to the latest electron version, by reinstalling obsidian (without uninstalling the prior version).
