### ISSUE TITLE
[FEATURE] Pronouns

### ISSUE THREAD

**Issue by KellyEH** [carlonicora/obsidian-rpg-manager#283]
## Scope

Pronoun options

### Describe the solution you'd like

I have player characters that use he/they and she/they, so it would be helpful to have these options OR be allowed to choose multiple options from the existing list.

Thanks,
Kelly

**Comment by sigrunixia** [comment]
We'll be sure to include this in the rewrite :)

**Comment by carlonicora** [comment]
ouch, pronouns are missing in v4... will look into it

**Comment by carlonicora** [comment]
@KellyEH 

version 4.0.2 includes the two new pronouns

Ciao
Carlo
