### ISSUE TITLE
Scenes stay attached to an Act when the dropdown is changed

### ISSUE THREAD

**Issue by raynbowbrite** [carlonicora/obsidian-rpg-manager#284]
When I change the dropdown on the Scene page, to move it to a different Act, it moves to the new Act, but also mantains the relationship with the original Act.  So the Scene ends up in more than one Act.
If I close and reopen Obsidian, the extra links go away.
[Carnivalle GA 1 - The Poster on the Tree.md](https://github.com/carlonicora/obsidian-rpg-manager/files/10714589/Carnivalle.GA.1.-.The.Poster.on.the.Tree.md)
[data.txt](https://github.com/carlonicora/obsidian-rpg-manager/files/10714594/data.txt)

**Comment by carlonicora** [comment]
Hi @vpaladino 

Thanks for the report. I will look into it and write a fix

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
