### ISSUE TITLE
Error creating a second campaign in the same vault

### ISSUE THREAD

**Issue by eaisley** [carlonicora/obsidian-rpg-manager#285]
### Summary
I'm on Windows 10, Obsidian version 1.1.16 and RPG manager v3.4.5. 

I have an existing campaign, and trying to create a second one in the same vault, but I'm getting an error "Duplicated outline indexService". 

### Detailed info

Existing campaign is in (paraphrased)
.../Obsidian/Vaultname/Campaign1/Campaign1.md

I want to place the new campaign like so:
.../Obsidian/Vaultname/Tabletop/Campaign2/Campaign2.md

In the sidebar, I click "Create new..." >" Campaign". It prompts for the title, and I select the default Campaign template from the dropdown.

This places Campaign2.md into the same folder as Campaign1.md. My Obsidian settings have new notes going into the Vault folder, and I've fiddled a few ways to try and avoid this (like opening a new note in Campaign2 folder, so that's my current view) but it always happens.

I get the following error popup:
"RPG Manager Error
One or more of the tags that define an outline or an element are not correctly configured and can't be read!
Please double check the errors and correct them.

Duplicated outline indexService
- Campaign1
- Campaign2"

Followed by a "Fix Errors" button which doesn't seem to do anything, it just drops me into looking at the new Campaign2.md, while the error appears in the right sidebar.

I couldn't find any info in the docs about this error, but I assume it's mad because there are now 2 campaigns in the same folder. 

So I manually moved Campaign2.md into the correct Campaign2 folder, however the error remains. 

(Edit):
I tried to create a new Adventure as well, but only Campaign1 will show in the dropdown, and not the new Campaign2.

I'd prefer to avoid creating a new vault for each campaign if possible. Please let me know if I can provide any more info, or what I might've done wrong. Thank you very much for creating this plugin, and for any help you're able to offer.

**Comment by eaisley** [comment]
Update, I exited Obsidian and reopened it. Now RPG Manager sees Campaign2 as the only campaign, and has filled in the formatting from the campaign template into that page, along with all of the links for characters, adventures, etc from Campaign1.

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
