### ISSUE TITLE
[BUG] Scenes are disconnected from Acts

### ISSUE THREAD

**Issue by max-dmg** [carlonicora/obsidian-rpg-manager#286]
## Scope

Scene 1.1.1.3. won't link to 1.1.1.4.
1.1.1.4. won't link to 1.1.1.5.
1.1.1.4. won't show in the Act's outline.

### To Reproduce

Steps to reproduce the behaviour:
1. I initially created the scenes using the Wizard, but deleted and created new Scenes manually (using "Create a new Scene").
2. Rename Scenes multiple times.
3. Delete and create more Scenes manually.
4. Manually [[Link]] to other notes, and change their relationship.

### Symptoms and attempts to fix

Some scenes have extra data from the Wizard, and others don't - I can't tell if this affects it or not, as the other working Scenes are Wizard and manually created.

1.1.1.3. was created by the Wizard, 1.1.1.4. was not.  I deleted 1.1.1.3.'s RPG manager data (in the "20" codeblock) but that didn't have an effect.

Scene 1.1.1.4. thought it was part of another Act, so I changed Scene's Act, but moving it to the correct Act had no effect on it appearing, and it thought it was still part of the other Act.  I disconnected it in the Relationship manager which removed it from the wrong Act, but it still only shows as "Unidir" in the correct Act.

Changing it to be "Bidir has no effect and it reverts back to "Unidir" when the Relationship manager is closed.

Manually linking them together with a [[NoteLink]] has no effect on listing or relationship.

### Screenshots

Note in the image, 1.1.1.3. won't navigate to the problem Scene 1.1.1.4, and that 1.1.1.4. also won't navigate to 1.1.1.5..

![rpgm_bug1](https://user-images.githubusercontent.com/68263412/230823401-8f542304-d091-4009-8485-e7631065989c.png)

Note in the image that Scene 1.1.1.4 is missing.

![rpgm_bug2](https://user-images.githubusercontent.com/68263412/230823484-ed61d977-ae02-46ec-8025-5041d63308af.png)

### Desktop (please complete the following information)

 - OS: Linux Cinnamon
 - Obsidian: 1.1.16
 - RPG Manager 3.4.5

### Additional context

**Great plugin**!  Would love to contribute at some point if time allows.

I hope that all made sense.  Can clarify if needed.

**Comment by max-dmg** [comment]
Yesterday I copied it all to my Samsung device, which it showed in the Act but the Scene was disconnected still.

Today I opened the vault on my PC, and it showed in the Act, and the Scenes were connected again but are in the wrong order (1.1.1.4. is #3 in the act, and rearranging them doesn't update it's index).  1.1.1.2. has lost it's "next" to 1.1.1.3, and both 1.1.1.3. and 1.1.1.4. scenes say that 1.1.1.5. is next.

After looking around, I found the "don't touch this" section, and changed the "position in parent" to show the correct position, and now everything works :)  looks like it was just getting confused between both 1.1.1.3. and 1.1.1.4. having the same position index.

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
