### ISSUE TITLE
[BUG] Location description wont change

### ISSUE THREAD

**Issue by FuriousOwlBear** [carlonicora/obsidian-rpg-manager#287]
## Scope

When creating locations, the description does not update when edited sometimes. This appears to only effect some location notes, usually new notes.

### To Reproduce

Steps to reproduce the behaviour:
1. Go to a location
3. Click on the edit symbol for a description
4. Enter a description and hit save
5. No change will be made

### Desktop (please complete the following information)

 - OS: Windows 11
 - Browser: Obsidian App
 - Version: 3.4.5

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
