### ISSUE TITLE
[FEATURE] Items object

### ISSUE THREAD

**Issue by InsiderPhD** [carlonicora/obsidian-rpg-manager#291]
## Scope

At the moment I've been adding all items as Clues, but this starts to get confusing when I'm trying to find out what items each Character has as I'm using the Clues -> Found property. My alternative is tagging the items with a tag called items and tagging clues as clues, but this doesn't solve the inventory problem. Another approach is adding a relationship and doing a regular obsidian link, however the relationship does show on the Character page. This is important for some RPG games as items could offer bonuses to players (I am playing Call of Cthulhu and books can give characters spells).

### Describe the solution you'd like

I'd like a new object called Items which shows on the Character page, this could be a very simple page with a description, image and details about the Item.

### Alternatives

Allow Clue relationships to show on the Character page and continue using Clues as Items using tags.

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
