### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by the1gofer** [carlonicora/obsidian-rpg-manager#292]
## Scope

if you have an adventure with the same name as a location, the RPG manager at the top of a Act Template will link to the Location not the adventure. 

### To Reproduce

Steps to reproduce the behaviour:
name an adventure  with a name
name a location with the same name
link campaign to the adventure

### Expected behaviour

Bredcrumb trail should link to the adventure on the act page, not the location

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
