### ISSUE TITLE
[FEATURE] Excalidraw or Canvas Support

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#293]
## Scope

> Determine Feasibility of Excalidraw or Canvas Support

### Describe the solution you'd like

"My biggest wish for RPG manager would be that I can plot out my campaign in excalidraw or canvas and then let RPG manager create the structure as files. I am a visual plotter"

**Comment by sigrunixia** [comment]
Adding to my to-do list to research [The Excalidraw Repo](https://github.com/zsviczian/obsidian-excalidraw-plugin)

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
