### ISSUE TITLE
[FEATURE] Switch to GH Pages or Publish for Documentation

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#294]
## Scope

Is your feature request related to a problem? Please describe.

> After using Publish and GH Pages extensively the past few months, I think that will result in a better flow of documentation than the GitHub Wiki.

### Additional context
This is the [Javalent Documentation Publish](https://plugins.javalent.com/home) I manage. What is very nice about it, is its very easy to have what you see in your vault, appear in the publish page. We could spin up a GH-Pages, but I'd be willing to help pay for the monthly publish to have that option primarily. 

This would also be a way we can show what campaign vaults look like.

- [x] #295

**Comment by carlonicora** [comment]
@sigrunixia let me understand this a bit better...

You'd like to create a vault with the documentation and use Publish to have it available online?
