### ISSUE TITLE
If We are able to freeze or have RPG-Manager optionally output its data as markdown, we can also make the plugin entirely Publish friendly.

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#295]
Currently, Obsidian Publish has no support for plugins. I have heard for a while this will change, but am unsure when. Several of us on the TTRPG side are doing our best to try to replicate the JS in a way Publish can understand.

In the interim, there are ways to freeze Javascript, or have a code block modal output markdown/html instead. Allowing this to happen would allow publish pages to not have to go through edits to host their content.

**Comment by carlonicora** [comment]
Let's re-think this with the new API
