### ISSUE TITLE
Add help or usage info for integration with Fantasy Calendar.

### ISSUE THREAD

**Issue by CodeSlinger42** [carlonicora/obsidian-rpg-manager#296]
The readme says that RPG Manager integrates with Fantasy Calendar, but when I enter dates in Fantasy Calendar format I get an invalid format error, and the date picker uses a standard calendar.  Please add a few bullets on how to get RPG Manager to use a Fantasy Calendar.

**Comment by CodeSlinger42** [comment]
I found the key in the release notes.  Might still be nice to update the readme.

Added the following to the frontmatter of my campaign.
```
fc-calendar: "YOUR CALENDAR NAME HERE"
```

**Comment by GionaCantarutti** [comment]
When i do that it just stops displaying the date. In the rpg manager data do you have to use `fc-date:` or do you still use `date:`?

**Comment by sigrunixia** [comment]
You may need to restart obsidian after changing the calendar over.

Additionally, you may need to try unwrapping your key:value pair of quotes.

`fc-calendar: calendar`

Its recommended the calendar name be one word and contain no special characters if at all possible.

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
