### ISSUE TITLE
[Survey]: Please take this survey.

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#297]
This anonymous survey is to decide the future direction of RPG Manager.

It closes end of day 2023-05-26.

https://docs.google.com/forms/d/e/1FAIpQLSduhZ5WK5-jZNy8u4hYAK-442SktaRdoi15JWwic50m8A5wCg/viewform?fbzx=-1124856630504213966

**Comment by mclang** [comment]
Tried to answer, but it seems to be closed already so I was late.
My bad, I didn't notice the date, but this issue should probably be closed...

**Comment by sigrunixia** [comment]
Ah yes, thank you for the reminder. :)
