### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by the1gofer** [carlonicora/obsidian-rpg-manager#304]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

The plugin seems to have just stop working after the most recent update.  I get the attached error. 
<img width="510" alt="Screenshot 2023-06-02 at 6 19 47 PM" src="https://github.com/carlonicora/obsidian-rpg-manager/assets/2140724/e2904f1b-d122-40ca-a15c-01bcc5d8f23c">

### Current behaviour

see attachment

### Reproduction

I really don't know.  After the update it seems to have been broken.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

1.3.5

### Plugin Version

3.4.5

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
