### ISSUE TITLE
[Bug]: Can't select bi-directional Relationship between two NPCs or two PCs

### ISSUE THREAD

**Issue by Kasenlys** [carlonicora/obsidian-rpg-manager#305]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

When trying to create a relationship between two NPCs or two PCs, we should have the same choice between "unidirectional" and "bidirectional" available, as for a relationship PC-NPC or NPC-PC

### Current behaviour

When trying to create a relationship between two NPCs or two PCs, only "unidirectional" is available.
The same happen for any relation happen for any items of the same type (i quickly tried with two locations, "bidirectional" is available for a relationship with a PC or NPC, but not with another location)

### Reproduction

Create a NPC.
Create another NPC.
Create a relation between the two NPC.
Notice that bidirectional is not avaiable

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

1.3.5

### Plugin Version

3.4.5

### Confirmation

- [ ] I have disabled all other plugins and the issue still persists.

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
