### ISSUE TITLE
[Bug]: Bi-directional relationship appears only on the item on which it was created

### ISSUE THREAD

**Issue by Kasenlys** [carlonicora/obsidian-rpg-manager#306]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

When creating a bi-directional relationship from a newly created NPC, between that NPC and a PC, the relationship should appear on both NPC note and PC note.

### Current behaviour

When creating a bi-directional relationship from a newly created NPC, between that NPC and a PC, the relationship only appear on both the note it has been created in (the NPC in this example).

### Reproduction

Create a PC
Create a NPC
Create a bidirectional relationship from the NPC note
Notice it is present only on NPC note and not on the PC note

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

1.3.5

### Plugin Version

3.4.5

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

It is a bug in my opinion (by definition of bi-directional, it should go in both directions), please confirm me if it is indeed a bug or if it should be a feature request

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
