### ISSUE TITLE
[Feature]: factions hierarchy

### ISSUE THREAD

**Issue by Krampus-update** [carlonicora/obsidian-rpg-manager#307]
### Please make sure this feature request hasn't been suggested before.

- [X] I searched previous Issues and didn't find any similar feature requests.

### Feature description

would be nice if we could organize members of a faction by they patent, rank, level or something like that.

### Solution

A possible solution would allow to set a propety in faction yaml like:
`faction: CTL` (CTL stands for Cult of The Lamb)

And then in (N)PC yaml like:
`CTL: Novice`
`CTL: Aprendice`

And well... it's kinda not a NECESSARY feature, but its nice to organization, just having a list of all members of the faction separated helps alot

### Alternatives

i kinda been using dataview to try to do something like what i suggested but its kinda annoying to set what i saying using dataview.

### Additional Information

i just want to say that this plugins its already SUPER useful, and its current state its super useful, and i noticed that you guys needed some help, if you guys need any help translate to brazilian portuguese, my [discord](https://discord.com/users/335956864321847306) will always be open S2

**Comment by carlonicora** [comment]
Hello!
Version 4.0 of RPG Manager has just been released. This is a complete re-writing of the plugin, and will impact all opened issues.
I am therefore closing this issue as it was related to v3.4 (now unsupported), but please feel free to re-open the task if the issue persists in the new version.

Ciao
Carlo
