### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by EldritchTranslator** [carlonicora/obsidian-rpg-manager#310]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

The button's font stays the same.

### Current behaviour

Upon activating this plugin, the button's font in all of Obsidian changes:
![immagine](https://github.com/carlonicora/obsidian-rpg-manager/assets/56313572/65f2d0b5-5cb0-42af-9821-5e5500a0abb1)
it becomes bigger and doesn't fit anymore inside the buttons.

### Reproduction

1. Download the latest version of rpg manager
2. activate it.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.4.12 and 1.4.5

### Plugin Version

4.0.3

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by carlonicora** [comment]
Hi @EldritchTranslator 

Thanks for the report. I have found the issue and I will check how to resolve it! I will keep you posted as soon as it is solved!

Carlo

**Comment by carlonicora** [comment]
@EldritchTranslator I have pushed version 4.0.4 that should fix the issue.

Please reopen the issue if I missed something

Ciao
