### ISSUE TITLE
[Bug]: 4.0 Update Ignores Readable Line Length Setting

### ISSUE THREAD

**Issue by lyao6104** [carlonicora/obsidian-rpg-manager#311]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Plugin respects the Readable Line Length editor setting.

### Current behaviour

In Live Preview/Edit mode, the length of a line always stretches to fill the entire screen, instead of being limited by the readable line length setting. Reading mode still works as expected.

### Reproduction

1. Launch Obsidian with RPG Manager and the Readable Line Length setting under Appearance > Editor enabled
2. Open any file with text in editing mode; the text should stretch to fill the entire screen.
3. Switch to reading mode; the text shouldn't take up the entire screen anymore

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.4.13

### Plugin Version

4.1.0

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

This appears to be caused by this CSS code, which forces everything to be max width:
https://github.com/carlonicora/obsidian-rpg-manager/blob/877e79732fffc04f768a7095d4723ae1bdcbdcbc/styles.css#L1326-L1337

**Comment by carlonicora** [comment]
Hi @lyao6104 
It is a conundrum, as removing the max-width will render the UI area super small. I am trying to place the RPG Manager UI in a Code Mirror extension to be loaded at the top of the page, but I am still fighting with it.

@sigrunixia do you have any opinion on this?

**Comment by chabad360** [comment]
Hmm, I went in and disabled the max-width style, and it went back to normal (and it wasn't too tiny, at least for me). If it's really an issue, perhaps you could make it configurable (assign the value to a css variable that's set on the body by js)? That way people could at least control how wide it is.

**Comment by carlonicora** [comment]
@chabad360 I will look into making it optional as soon as I manage to find the time and understand how I can make it happen!

**Comment by carlonicora** [comment]
Fixed in 4.1.5 by adding a new setting to toggle the full width
