### ISSUE TITLE
[Feature]: RPG Database & Faction Hierarchy

### ISSUE THREAD

**Issue by WttBe** [carlonicora/obsidian-rpg-manager#312]
### Please make sure this feature request hasn't been suggested before.

- [X] I searched previous Issues and didn't find any similar feature requests.

### Feature description

Hello,

Thanks a lot for this crazy plugin. The new version is even more polished, and you did an amazing work!

I roamed through all the information given, but did not find any information concerning a potential "RPG Database" or faction hierarchy (they are mentionned in the closed issues, but were not taken into account as far as I know). 

About the first one, I run my campaigns in a unique world, and I would like to access the same locations, PCs, NPCs, factions, items or monsters for separated campaigns. It does not seem to be possible at the moment.

Concerning faction hierarchy, it would be really interesting to be able to divide factions members into some sort of hierarchy (leader, apprentice, novice, etc.).

Anyways, thanks again for the good work.

### Solution

* Add an external location to store data which could be used in multiple campaigns
* Add the possibility to classify factions members into ranks

### Alternatives

/

### Additional Information

/

**Comment by carlonicora** [comment]
hi @WttBe 

There are two things:
- global elements
- organisation of children

For the first one, the global elements, it is already implemented. When you create a new element, just tick the "_Make this element available in all campaigns_", and the job is done.

For the second one, the main issue I see is where to save the organisational structure. I will think about it and see what I can do!

**Comment by WttBe** [comment]
Hi @carlonicora,

Thanks for the answer, and for the future thinkings on faction hierarchy.

I hadn't seen the option to make an element global, my apologies! This is great!
