### ISSUE TITLE
[Feature]: Trackable Error on bad Yaml

### ISSUE THREAD

**Issue by xeroe** [carlonicora/obsidian-rpg-manager#313]
### Please make sure this feature request hasn't been suggested before.

- [X] I searched previous Issues and didn't find any similar feature requests.

### Feature description

Ive had the problem, that on multiple occasions the plugin wouldnt render anymore if there was a yaml error in any file.
As ive seen here https://github.com/carlonicora/obsidian-rpg-manager/issues/211 that is a known behaviour and can be somewhat debugged using the console.
Since its not possible however to see which md file is causing the error it would be nice if the plugin could output a trackable error / prompt to let the user know where the problem sits.

### Solution

Trackable error message for bad yaml

### Alternatives

 - 

### Additional Information

https://github.com/carlonicora/obsidian-rpg-manager/issues/211

**Comment by carlonicora** [comment]
Hi @xeroe 

thanks for the suggestion. I need to check if I can understand which file cause the issue. Will dig into it.

**Comment by carlonicora** [comment]
@xeroe right now if there is an issue in one of the files, the plugin does not block all the files, and report the name of the file with the error in the Inspector Console

**Comment by xeroe** [comment]
sounds great thank you :)
