### ISSUE TITLE
[Feature]: URL attribute type

### ISSUE THREAD

**Issue by Minivera** [carlonicora/obsidian-rpg-manager#315]
### Please make sure this feature request hasn't been suggested before.

- [X] I searched previous Issues and didn't find any similar feature requests.

### Feature description

When creating things like locations, monsters, objects, or other elements that I take from sources online, I would like to be able to keep a quick reference as an attribute to go back to that external URL easily. For example, I have a bunch of objects I have created on D&D beyond that I also added to my campaign in Obsidian. It would be very useful to have a URL custom attribute I can add to those objects that open a new tab to the D&D beyond stats. I can add them to the content of the document of course, but an attribute is easier to manage.

### Solution

Add a URL type for custom attributes that renders to an external URL, like you would get when using `[]()` in markdown.

### Alternatives

I currently use a text type attribute, which is not clickable. I can easily grab the url and past it in a browser though.

### Additional Information

N/A

**Comment by carlonicora** [comment]
@Minivera thanks for the suggestion, I will look into it for the next release

**Comment by carlonicora** [comment]
@Minivera added to 4.1.5 and released

**Comment by Minivera** [comment]
Missed this notification, thank you!!
