### ISSUE TITLE
[Feature]: List of all campaign objects sorted by type

### ISSUE THREAD

**Issue by CucumisSativus** [carlonicora/obsidian-rpg-manager#316]
### Please make sure this feature request hasn't been suggested before.

- [X] I searched previous Issues and didn't find any similar feature requests.

### Feature description

A list of all objects sorted by the type. Ex. Player Characters, Non Player Characters, Adventures and so on

### Solution

In my case it would be helpful to see grouped objects of all types ex. all the player characters, all the nps, all the subplots

### Alternatives

You can manually click on every note in your folder or select sessions and adventures on the campaign screen, but still there is no easy way to find all the characters

### Additional Information

Thanks for the plugin!

**Comment by carlonicora** [comment]
@CucumisSativus where would you like to see this list? In the campaign?

**Comment by carlonicora** [comment]
@CucumisSativus Let me understand, you'd like to see the list of elements, grouped by type, in the right area?

If not, draw me what you envisage so I can understand it better! :)
Thanks

**Comment by CucumisSativus** [comment]
@carlonicora it could be basically anywhere, but what is important for me is the whole list and groups

**Comment by carlonicora** [comment]
@CucumisSativus Why don't you add me on Discord (carlo_storyteller) as I need to understand what you need a bit more into details
