### ISSUE TITLE
[Bug]: It seems that RPG Manager forces to full width window tab

### ISSUE THREAD

**Issue by yungaro** [carlonicora/obsidian-rpg-manager#318]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Line width size to be adjustable (any rpg manager note), just as when sidebar opens and tab resizes.

### Current behaviour

I cant adjust line width (any rpg manager note), because RPGM is somehow interfering with Lie Width Slider plugin, or viceversa.

### Reproduction

1. Install Line Width Slider
2. Install RPGM
3. Adjusting lie width doesnt work anymore

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.4.16

### Plugin Version

4.1.4

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

Please fix RPGM forcing full width window tab, or make it compatible with "Line Width Slider" plugin.

**Comment by Kantana** [comment]
Same issue here when using the Minimal Theme. Any changes to line width made in the Minimal Theme Settings plugin are not having any effect until I disable RPG Manager.

**Comment by carlonicora** [comment]
this is being discussed in #311 and I will try and update the plugin when I find a suitable solution

**Comment by carlonicora** [comment]
Fixed in 4.1.5 by adding a new setting to toggle the full width
