### ISSUE TITLE
[Question/Help] Wrapping UI in Collapsible Callout?

### ISSUE THREAD

**Issue by jhilker98** [carlonicora/obsidian-rpg-manager#319]
Hey there, thanks for creating this - I'm currently using it to help with fiction. I'd like to be able to keep the UI in a collapsible note callout and have some relevant trackers/other information on the page as well. However, whenever I had tried to place it in a callout, rpg-manager failed to detect it as a campaign. Is this possible?

**Comment by carlonicora** [comment]
@jhilker98 unfortunately the data in a callout is not seen as a codeblock by obsidian, therefore this cannot be achieved.

A code block is contained inside a specific construct in the markdown file in obsidian. If you add it to a callout, obsidian does not read it as a block containing the code, hence the plugin can't read it.

Sorry :(
