### ISSUE TITLE
Add possibility to use own templates

### ISSUE THREAD

**Issue by namtrah** [carlonicora/obsidian-rpg-manager#32]
For each RPGM type (Campaign, Adventure, Session ...) allow the user to define his/her/their own template files. I foresee this as a setup option where the file (or folder to files with a specific name) could be used to append to the main RPGM Frontmatter (for the tool itself). This way it could also be possible to use other tools like obsidian-templater and CustomJS to create more dynamic templates.

Please keep in mind that not only the content of the note would be in the template but also more frontmatter (RPG specific frontmatter used by tools like initiative tracker, or others)

**Comment by carlonicora** [comment]
Note to self:
- Setting to define the Template folder
- Internal Templates to mimic the current templates
- Type-Specific templates to be identified through the tag `rpgm/template/{type}` where type in {campaign|adventure|session|...}
- Generic templates to grab everything the user has in their Template Folder

**Comment by carlonicora** [comment]
Released in [v1.1](https://github.com/carlonicora/obsidian-rpg-manager/releases/tag/1.1.0)
