### ISSUE TITLE
[Bug]: Cannot Create new Entries 

### ISSUE THREAD

**Issue by Marlight777** [carlonicora/obsidian-rpg-manager#320]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

I expect when I click on create new X to have a window pop up so I can name the new item. I have another player experiencing the same problem. 

### Current behaviour

I get a blank box that will not load any creation options. Also all current entries can only be visible in source mode
![image](https://github.com/carlonicora/obsidian-rpg-manager/assets/63486169/b0fe85a9-3096-4fa9-b972-8c63fcf9d799)

### Reproduction

 Create new X
 No option to move forward from there

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.4.16

### Plugin Version

4.1.4

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by Marlight777** [comment]
![image](https://github.com/carlonicora/obsidian-rpg-manager/assets/63486169/9f5d5e22-1266-4701-bd69-884bcac0f5a5)
after posting this, we have another person with the same issue, with a few hundred hours in.

**Comment by carlonicora** [comment]
@Marlight777 have you checked if the same issues persists using the Command Palette instead than using the options on the right?

I am not sure I understood the "_hundred hours in_" comment

**Comment by carlonicora** [comment]
@Marlight777 also, can you please screenshot the Inspector Console? There might be issues there

**Comment by Marlight777** [comment]
![image](https://github.com/carlonicora/obsidian-rpg-manager/assets/63486169/b2cd1ac5-4b56-4a5a-9da5-6283c543209d)
using the command pallet for new entry I get the same.

Sorry I should have been clearer this user has hundreds of hours. He is the one that got us into Obsidian and your plugin :)

![image](https://github.com/carlonicora/obsidian-rpg-manager/assets/63486169/d828a577-1f6c-4765-acd9-8a6579af977d)

Few issues found:

![image](https://github.com/carlonicora/obsidian-rpg-manager/assets/63486169/812db41c-176b-4c69-a78c-d9286da84afe)

Trying to figure out how entries are "edited" when some have not directly been accessed for almost a month. Connections have been made yes, but the actual text has not been touched for quite a while. I am in graph view 90% of the time. 

I will try to post more precise language, thank you so much for helping with this. Would hate to lose all of this work :)!

**Comment by carlonicora** [comment]
@Marlight777 update to the latest version (I just released **4.1.5**) and look again at the inspector Console. I have added some additional logs when there are issues with YAML (**like in this case, I am sure one YAML is not properly formatted**).
With 4.1.5 you should be able to create new elements, but just in case, check the files that are showing the error.

Let me know if the issue is sorted with 4.1.5

**Comment by Marlight777** [comment]
![image](https://github.com/carlonicora/obsidian-rpg-manager/assets/63486169/172382bd-ddad-46e4-bb44-37abfe534c79)

It seems to all be working now :) the view is a little more restricted, like the page is a little squished, but the most important thing as that all players notes, and many hours for everyone has been saved :)

![image](https://github.com/carlonicora/obsidian-rpg-manager/assets/63486169/598ef77c-d3ea-481c-bb97-ef171905434f)

having all of them update now, I appreciate you!

**Comment by carlonicora** [comment]
@Marlight777 happy this works

PS: you can make the view full width from the settings!
