### ISSUE TITLE
Does fantasy calendar integration no longer work?

### ISSUE THREAD

**Issue by vincenzobrosco** [carlonicora/obsidian-rpg-manager#329]
🇬🇧 
Before updating to version 4 of the plugin I could enter event dates using the calendar created with Fantasy Calendar, now I can only use the Gregorian calendar. Does the integration with fantasy calendar no longer work or am I doing something wrong? I attach screenshots

🇮🇹 
Prima dell'aggiornamento alla versione 4 del plugin potevo inserire le date degli eventi usando il calendario creato con Fantasy Calendar, ora posso usare solo il calendario gregoriano. L'integrazione con fantasy calendar non funziona più o sto sbagliando io qualcosa? Allego screenshot.

New input date option:
![immagine](https://github.com/carlonicora/obsidian-rpg-manager/assets/42866436/21be500b-1095-4ad3-b1dd-89ece9e8a074)

My fantasy calendar
![immagine](https://github.com/carlonicora/obsidian-rpg-manager/assets/42866436/5563cfce-a07c-4761-8fd2-7cf5cfd02249)

Note:

🇬🇧 
The fantasy calendar plugin is currently no longer maintained. Maybe I can integrate another plugin?

🇮🇹 
Attualmente il plugin fantasy calendar risulta non più mantenuto. Forse posso integrare un altro plugin?

![immagine](https://github.com/carlonicora/obsidian-rpg-manager/assets/42866436/a79c5d79-35cc-414b-ba84-86dbf28f3ba8)

**Comment by carlonicora** [comment]
hi @vincenzobrosco 

Fantasy calendar is being updated and at the moment it is no longer supported. The new package is still in beta, and I will add the support for it when it is released and stable.

**Comment by vincenzobrosco** [comment]
thank you!
