### ISSUE TITLE
Improper Tag Array in Unrelated Notes Breaking RPG Manager

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#33]
I finally located this issue.

In one of my older notes, specifically for a "timeline" style note. I had a template with YAML tags that had a tag array in the form of:

---
tags: key 1, key 2, key 3
---

Obsidian itself works despite it not being a proper array, as shown in the following screenshot.

![tagerror](https://user-images.githubusercontent.com/68425372/189537695-ec7ffdcd-f932-4419-8324-9873467b6eb7.jpg)

The array should be.

---
tags: [key 1, key 2, key 3]
---

Once corrected, then Obsidian changes to look like so.

![tagfixed](https://user-images.githubusercontent.com/68425372/189537720-12485ae2-f1d7-41c3-849b-35f5166fa867.jpg)

I checked other variations of tags in YAML, with the exception of tags: #tag as it is hopefully well known to not use hashtags in YAML, but it may be worth to investigate that as well.

Attached also is the console log that is created when the error occurs. 

[obsidian.md-1662854035885.log](https://github.com/carlonicora/obsidian-rpg-manager/files/9543015/obsidian.md-1662854035885.log)

**Comment by carlonicora** [comment]
@sigrunixia writing the tags as 

```
tags: #tag1, #tag2, #tag3
```

in the frontmatter is not a correct yaml. you should alway write them as
```
tags: [#tag1, #tag2, #tag3]
```

by fixing that, the issue will sort itself.

I will push a fix to catch this edge-case in a minute

**Comment by carlonicora** [comment]
Small fix released in [v1.0.6](https://github.com/carlonicora/obsidian-rpg-manager/releases/tag/1.0.6)

However, if the tags are not written in a correct yaml, RPG Manager cannot parse them :S
