### ISSUE TITLE
campaignId undefined after 1.1 update

### ISSUE THREAD

**Issue by Sandman2055** [carlonicora/obsidian-rpg-manager#34]
I get a "TypeError: Cannot read properties of undefined (reading 'campaignId')  when attempting to open notes after the 1.1 patch.  The following note was fine before the patch.

---
alias: []
tags: [rpgm/outline/session/1/7/2]
synopsis: "A local tavern seems like a seedy bar but is actually the lair of a notorious gang of thieves - and maybe Vampires"
dates:
 session: 
 irl: 
completed: false
---
```RpgManager
sessionNavigation
```

Body of note

**Comment by carlonicora** [comment]
Improve error management during data creation, both at startup and during runtime

**Comment by carlonicora** [comment]
Error management implemented to avoid these errors in [v1.1.4](https://github.com/carlonicora/obsidian-rpg-manager/releases/tag/1.1.4)
