### ISSUE TITLE
[Feature]: World Folder

### ISSUE THREAD

**Issue by KoltonHarris** [carlonicora/obsidian-rpg-manager#343]
### Please make sure this feature request hasn't been suggested before.

- [x] I searched previous Issues and didn't find any similar feature requests.

### Feature description

First of all, this is an incredibly awesome plugin and i cant wait to use it more! There is only one thing that could make it better, a "World" folder option. This would be a folder that can contain monsters, deities, locations, etc. that are used across multiple campaigns. 

### Solution

I think the best solution to this is making the vault qualify as the world folder meaning that you would be able to add locations, deities, etc. to the root of the vault or a separate folder dedicated to that topic. Then those files could be linked to as normal across multiple campaigns.

### Alternatives

Alternatively, maybe there could be a "World" folder in the vault that contains all the information (locations, deities, monsters, etc.)

### Additional Information

This is taking inspiration from [Kanka](kanka.io) and their topic hierarchy system.

**Comment by carlonicora** [comment]
Hi @KoltonHarris
 
When you create a new element, you can check the "_Make this element available in all campaigns_" checkbox and it will save the element in an "Assets" folder and its elements made accessible to all the campaigns in the vault.

Ciao
Carlo
