### ISSUE TITLE
[Bug]: discord-link broken?

### ISSUE THREAD

**Issue by ZorkfromZork** [carlonicora/obsidian-rpg-manager#351]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

When you click on the link 
https://discord.com/channels/686053708261228577/1022806716343144518 
It should open theoret discord forum.

### Current behaviour

It does not open or leads to an empty page.

### Reproduction

Click on Link in description text in GitHub readme.

### Which Operating Systems are you using?

- [X] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version Check

Not relevant

### Plugin Version

Not relevant

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

Restart / setup⁰ discord page?

**Comment by carlonicora** [comment]
Hi @ZorkfromZork 

The link works for me. Are you part of the Obsidian Member Group? Maybe that's the issue, I think once you are, you will be able to join the channel
