### ISSUE TITLE
Feature Request: Include image URL's and/or a link in the "image" key in Frontmatter

### ISSUE THREAD

**Issue by Pachtjuilaard** [carlonicora/obsidian-rpg-manager#40]
I think only being able to use images that have exactly the same name as the current note is a bit too stringent. Having the option to include image links would make including images more flexible, and doesn't require you to have the image saved on disk.

**Comment by carlonicora** [comment]
Hi @Pachtjuilaard 

You have a good point. Will add this requirement to the upcoming v1.3

Ciao

**Comment by carlonicora** [comment]
Released in [v1.3](https://github.com/carlonicora/obsidian-rpg-manager/releases/tag/1.3.1)
