### ISSUE TITLE
Feature Request: Check aliases of characters/locations/factions/etc. for relations

### ISSUE THREAD

**Issue by Pachtjuilaard** [carlonicora/obsidian-rpg-manager#41]
I would like to be able to refer to relationships with other characters, locations and factions by their aliases, this would make creating relationships more flexible than it is now.

**Comment by carlonicora** [comment]
Hi @Pachtjuilaard 

Big changes to the way I handle relationship in v1.3 and those will solve the issue.

Stay tuned

**Comment by carlonicora** [comment]
Released in [v1.3](https://github.com/carlonicora/obsidian-rpg-manager/releases/tag/1.3.1)
