### ISSUE TITLE
Expanding the list of pronouns

### ISSUE THREAD

**Issue by thegiftofgabes** [carlonicora/obsidian-rpg-manager#59]
There are many other pronouns besides he/him, she/her, and they/them. Some people even may use a combination of those.

Here are some of of the many resources available on the subject:

https://www.lgbtqnation.com/2022/08/incomplete-list-gender-pronouns/

https://uwm.edu/lgbtrc/support/gender-pronouns/

https://lgbt.uni.edu/pronouns

**Comment by carlonicora** [comment]
@thegiftofgabes the best way to do this is for you to list all those you think matters (your experience matters here)

The ones available now are:
- them/their
- she/her
- he/his
- 
Let me know who other ones you'd like me to add.

Ciao 
Carlo

**Comment by cjolson** [comment]
For monsters, I sometimes wish I could add `it/its`. It's kind of related (though different intent than the inclusion of LGBT pronouns).

**Comment by carlonicora** [comment]
Added the ones from https://uwm.edu/lgbtrc/support/gender-pronouns/ plus `It/Its/Itself`
