### ISSUE TITLE
Refactor Relationships

### ISSUE THREAD

**Issue by carlonicora** [carlonicora/obsidian-rpg-manager#65]
How can I manage the locations organisation, including parent/child relationship, so to easily manage/read them?

**Comment by carlonicora** [comment]
**NOTE TO SELF**

Currently the relationships are organised in 4 different ways:
- Direct
- Direct in Frontmatter
- Reverse
- Reverse in Frontmatter

These are created in order to limit the visibility of certain relationship (creating boundaries for the relationships).
There is the need to update the system to simplify and extend these relationships.

The relationships needed are:
- two ways relationships (pc/location)
- one way relationships (subplots/events)
- parent/child relationship (location/sublocation)

**Comment by cstby** [comment]
For parent/child relationships, it may ultimately be better for users if the parent is linked in the child's frontmatter. In most cases, the user will be creating a child location when the parent already exists. In such cases, they currently need to switch over to the parent to establish the relationship.
