### ISSUE TITLE
multiple campaigns/worlds

### ISSUE THREAD

**Issue by matthewbivins** [carlonicora/obsidian-rpg-manager#73]
Hello! 
This plug-in is brilliant. Thank you. 

I do not mind the various content types (scenes, NPCs, PCs, etc.) being auto-sorted into folders, in fact it is very convenient, but what if you are playing multiple campaigns but do not want to use different vaults? Is there a setting that might allow me to use one attachments folder but choose a Parent Campaign folder for each campaign/world?

Many thanks!

**Comment by carlonicora** [comment]
Hi @matthewbivins 

If you place your campaigns in different folders in your vault, the subfolders will be created in the campaign folder.

So if in your vault you have two campaigns:
- Campaign1/Campaign1.md
- Campaign2/Campaign2.md

When you create an adventure (_for example_), it will be created in:
- Campaign1/Adventures/newAdventure.md if the adventure is created in Campaign1
- Campaign2/Adventures/newAdventure.md if the adventure is created in Campaign2

You can also disable the automatic move in the settings

Ciao
Carlo

**Comment by matthewbivins** [comment]
That is perfect! Grazie mille!!
