### ISSUE TITLE
Easier access to current / most recent Adventure, Act, and Session.

### ISSUE THREAD

**Issue by cjolson** [carlonicora/obsidian-rpg-manager#75]
On the Campaign page, the sections are ordered `Adventures` > `Acts` > `Sessions` > `the rest`. And within each, they're ordered with the oldest at the top and the newest at the bottom. 

- Sorting newest to oldest might be nice since the most relevant info for me is likely the most recent adventure/act/session. 
- Though beyond reversing the order of the individual sections, it might be even better to have the "Current Adventure/Act/Session" grouped together near the top. I assume this would be more effort, but it I think it'd be awesome and very user-friendly.
- And as a bonus thought: I'd love if Player Characters was first for the sections. Adventures/Acts/Sessions/Events/etc can get really long – but Player Characters generally maxes out at 6~ active PCs and is one of the most essential pieces of info for me to see as I do any work on my campaign.

Definitely feel free to explore other solutions. The main thought I have is "I want to see the most important info first: the PCs and the _current_ campaign files."

My workaround might be adding my own dataview codeblock before yours that displays that info? TBD.

**Comment by carlonicora** [comment]
Hello @cjolson 

I can certainly try and organise the list with the most recently edited first.

Good food for thoughts, will add it to v2.1

**Comment by cjolson** [comment]
@carlonicora I think having links that are easily accessible is what I have in mind so I can quickly go to those files. This is  how I set my campaign page up now (though I'm likely to tweak it). 

````
---
type: Campaign
alias: 
tags:
 - rpgm/campaign/1
completed: false
synopsis: ""
settings: Agnostic
dates:
  current: 
---

```RpgManager
campaignNavigation
abt:
  need: ""
  and: ""
  therefore: ""
```
---

## Campaign

> `[[Link to Current Adventure]]` >  `[[Link to Current Act]]` > `[[Link to Most Recent Session]]` 

``` RpgManager
campaign
  exclude: [Adventure, Act, Scene, Session, Event, NonPlayerCharacter, Subplot]
```
---
## Notes
-

```RpgManager
campaign
exclude: [Character]
```

---
# References
- 

````

<img width="1056" alt="Screen Shot 2022-09-28 at 9 52 01 AM" src="https://user-images.githubusercontent.com/18406537/192796949-f8e02cb6-a756-428f-9b93-e92b4754d0ff.png">

**Comment by carlonicora** [comment]
Note to self:

The parameters to identify the current adventure, current act and current sessions are not needed in the frontmatter, as they are only read inside the code block itself.

**Save the information in the code block YAML.**
