### ISSUE TITLE
Multiple Instances of NPC in Locations codeblock

### ISSUE THREAD

**Issue by cjolson** [carlonicora/obsidian-rpg-manager#77]
If I tag the location in the NPC YAML and then the NPC in the Location YAML, I see both instances of the NPC in the Location codeblock (but this isn't true for the Locations in the NPC code block).
<img width="1032" alt="Screen Shot 2022-09-27 at 10 51 25 PM" src="https://user-images.githubusercontent.com/18406537/192676598-9a7b4625-aa2b-46ea-86b4-82d8608aaf60.png">
<img width="1032" alt="Screen Shot 2022-09-27 at 10 51 19 PM" src="https://user-images.githubusercontent.com/18406537/192676603-519ae513-9731-4154-af3a-91df8dfd69eb.png">

**Comment by carlonicora** [comment]
Hi @cjolson this is fixed in `v3.0` and it will be released next week
